---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgAx+eJMHf8kXvpRxoqiayZEwlNCXp4/wrjtoWwRhTy30eBvnFXr5RPw2PiJVaMYumBv5zf71UuXWQe9nKF/ONeggrmr33E8lQbfw5SwdOI0i4nP6i//yITs7f4pqa4XlnsJi9Ztq6ALlU3jUg4pkzIPE2fJSi2bMdR68X+HeiFRFS4BUgyvTqgwqRw5Vmap/I5Pm2cGTJe3rG1PFytelJkNm9UOmsxEA/IFpX0knjj2B4FCnCID9fc+2sNY0lXXKvSsjL58gM/srNXT3d8fj30u2mY9DtVxtuxFrkwHPwMEp+lfrnDknJZVAIFaJA8bHtb1RH1SLIplYKO/lkSs8iQoXZytawMirI6idJwNZXTZJXTD3N86tjp1e7PnJaOQNvSC5Dp7bA4i6BEdXjErqywvXzmLgmJZLmMavE9cxShsdN5KK/1v7JSaUC9jRli0jnjF+Kk6hN3e1qUgWsJ/IxYc/2tZHQZfPF4gDpywOdpg21GPKO42cslpmrvpuRzZxVQSXvD5B1E3MIyYPOKjC24GTG5jp/jnzt5B2voeBzuZLmqAKuwGepf3Xe5WvUuayUv9gtTtR3hoAx/v1HVL1AA76Qw+1Qmha3gOrl/haqYRGHI+UtS09H4F2iJRdOmWaa5EKsGVR+Um/q7ZCgn0hsjCWHih4yTBRGTGzSE7NZddLTkL1pLt1y39yrFCo/22dl+WwNZTV4wsDYigdmPV5K271UUcGCi1WSadAolmhZcx9369FrKfixVgJOT2lnJVlSQFbWjJMTwp8FAQenTrK3lObdzbtoHwNQvMHFkC0ZZ2n1+eVScjScA04J51kqNSO665XUxPlVhwykvQNMVCR/DtdTuHDAqAPqreOJx0o75F29eDpAEyuSXAhOD4c6GhtbptL+EypxaCP4SVMVf04BOttXmOzsoAdh5N5rYuxtURXGHfo/Z83tzOqg==
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
