---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBv0nnUJKPSS/WXkBeTQKkVM/l+cC0DGmYU4D99hAO2fUxguurMsmlC9C+/2hvZ96TU9LV+F7mKK/xhtW00IK/6xMgSdKmpMtl6HwqI/t+MmhUlTfRmW+s1Y2ppiI2SiqEc1AilI8Lqw25wXQLKsOvM04496rYYF7jHc9I5OD6SmmRzJnplhSmmxgmJwAgWn1esOFPr5n0l1pgYRhf0C6Dhbu8b6fMWIcTF5MHUAerL/7mMLh9ZMskQ4zkco42PFNFpzkJWXYSjPlr2ZzOUyS6xCBLproyuFIX+lZD9koOVqubc4LHepqNIRGwdH1TfHdKEBtodSgbDw0LGowfRe5O3DWyZHKs4EAL0MKPTw5j+uSI6QNHq979ySCXLHjTL5Jd/UZR4jbg2sFg255xVhlDG4EHReIWEGu0qsyu267y4Pef6+nOB5VKTpZGhYOTv1EMQc3NEMpy5Kufdwjm61Q0ey8b3D/1wH+5yn6xKbsWNXOZURtC5qN4op3Ee0Vd7QQ/45ZVmXBeBTj0IAxhqIn4cMpPFlG1TrigTpyPqVciNiDH/blfigrFRIi+zP5sBgzvTMXtwQP8PZhaM1uRFBejivegErJys9PbC9CGroKGTFtFPUm89iWnlb27cE4hJnfQJQ0nX5IhPHu64ZpDhvPQ5otUvhuAcSkIshE31rL8xr2CjAX+T/Zyl84Bb0BxFMEnGCjm2e0jPSsFAJCkrH5F0RCklXBL1QTr3pb+/nNFq5A==
    username: AgALgE/l8Y/TAoEZR+fKhF8daWXZOESWUtT4IWSDBJbC7XdXOa5k15RU1TkBQD2cwbcGGjbrRg4HHtbI0EEf3syYXfg1IkPHIDTrPcLKvAORsugz5ZcR+p1Ds28iKZ68fg5tu5Ou2paXlTqtMziFByYSvQxzauL5UFyj/feBXsGulG5yJxJoFuYY/4zU0kI7batzV0JME9BSWOPXMJiCfCA/NsiSd41jghyylFzAyJLQIIRcZ2HywqxMqhZCi4iY6hNW8SlP4d1e0reFP6lVMZcG65PfKIVtmP9BPTNSH62wL1MQY7h8zDuj6QTX9RWN7Kl5BJ2XHQoAgJcXqAUZQaiA7Uv/8GYpz1CaasZm5hd3OZnjY9fUIbg7UU9g8sgnd9Ec/59cn911fHRSIq8JGwsXz4U28qLZoTb9BgRc3zx1xaS9bFCWsGc8dyK9CGlojxrtBIAcBbZd49yqHRYe6KFFa+hZne7VqRpfPgeyqY7HaezP/gvITPPCcPVepc2S4fugtnYs9G4WMueQ46mx8cF1yV53sDEY5rosGZaV1o/5swV7DEXZC9CboX2kqEOyYeJFZ1yLpWb2s6Cd6YsW5mmsPy8tcwHs/AP+tEIb7js0B9sbCvSP+NIsWHbRuux/G8s9BuAwFdgavh1joib0KVfHlMUwVJ7z3eOwhuJh1piHxzCKpYPnrXKCQZzw+4n4ZDkZkpftfZ4FZzTgq0WKzgkFRWay
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
