---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBpK/ItfbBAkwIhqpfXGzgR5Wk+ZZZAggRvtMIaGFW1mrv9mrwJDMXOewDt2ZlNBA+14XuXFxqjm9VZ24JtncDej3597E6u9XI4aARv/yH2bfuFCcON+2uUbMf+8kxCJLTDZX770uiLhfTl4B10envbPFxClVs1PnY5fZFh+HfBbBidlptfWu0/feQ9BIZuH4kI7amLbtQGjRlZ8WBvrA0/FoxNWseSBLQPXgVNBFXldYLeuf1KPfzNNr4yTRTLizKHl9JhcYl61elK9uOw7o5DkpHa4zQCibOgEVgdq6UeGx8B95EtQlXacrXzwD1MC7udkYiUaXWw/B07XVTsFO+jGY6vJ2irgSW1Nob+UiUETV21qxURF8/LrwVrGT1B6vnWNdGrW5tTqVAb95geLT01RWicYVkayZgVzgMZ8YGDwv1gxpF2VJsu7yOKIdWXQMUTUPz5VbO1OChFpnlRVH9bmmjM83uL809gw/9N844dRabRUZ5TWT7LwMOaTTXRkln6Rq0ObyTdedbemTVit6hjEbjOww3LagWeyHa5qraVJE3Jw/mIdFObECow0f6v/fuOhwBXKkwLu5jVQlqpJJPtSnhBjEFnXrZGvoOvIkJdQCUmHwFG/yasO6blAPNsoRdDTX81Tlf9NY5lwWdpcumUcqiJWoRwxEYYSP48rr0w7P5V2r6L/d8blfuO4PnHAoUNGlpxg1wvSHmGMoBV7lC/oLOlRCUfRnKbmtWa+3DbAw==
    username: AgBMOxV1CV3J7loL2YMLDPzWs4ibT7UmsL6DPN7q+XwFG7pQZmq+KlH1t5NW+fHOoYpumOKsOstlNylJrjcXLSKfuK+xGb/c28MMxtGlMJkfHxQBFHX7fqdyqOJ5SJBfMCd3aOfZb3qKamB2n9qHmkKiz/eMRxaihJxjqGCksGPML0+JvYCpLB7JsnjRLyiYY8HVDlh8f62p+89cgp1oaUl/lsNlrcK8C6IXvBoS9q+N18CX62roCysOVOo78Ng2XPR3U8N/pqIP1xwFgZPTgpkHDu48Yo8oWko+LcMP+Ddaf+j7HqJcLwrV0a1U9ZCRsOQakipkFuWblt1JN15nBKrfvCZ+jUit3yPP7PPll4EIQaD4cpGrF15GssZyhp6QwZ9JCYEqc65tf+HNH5SuWQ2WL+GNwWJYQ4W7FF6Kx3STP3eWFFf1jIlLZux11J9yRfltmSnyhuA2Z43S3GTmUqT7mhcsegG0F3QnI9qzapEZrB4JEeGsS5MJpBjHytEiU2bZYMQ7ErQ5wRisI0dgCL9/GdHJlc/Ssad9OB3o9oAesIuKmtFSew5JQgFk5tLfYidIL3I4mJqupnvy/rdYfq2AR2nyq7dNyzo2OKFBV1T1kEVbEF39JSbx2EiqdIYcgipZUfRYNDYs7y/Cg3ChX4XhXMpMCrJlU4AYiWrVWxBkHTMJ0xmjH1B/bcNCgneLz2CfW5Ou00Wccxgmvws7ro+iPdA7
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
