---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgC1MO32zZS3qdDRg6j0hcf4GTjzZpsBRUC0/BSz95DSbBOOaq+SceZRV3dTCpd0kgaj6YCEFgjRmM5ufCYf30PS0Wq3XscEDLPEG8ERzuyM4N7JhiaU/GRIvIzEYVvTkg6/NErNvos2Q6NrDoR50l6z/+xrGMK4mMCW07hd0ebG6/WlDtgupvNpqSe2EEtTmSocWrUa6XPaNkdJpyqwqhYo4ot03BLjJQrmv8o0eVHO8I1Sa0nllyaiJjDXB6H3gJ+UbeNUWav0OqQ9cvFQDRRR7LiWZqFy6rFC02lFahpzj86iWxHEWWjSbC6GHym+X90LMppbMnT4Vvkkm0GI4fthOP2zXYKqfGBM9yWbTPF/xGExxx9u5g3SryVnn2QPdlNiIC4tjxAL4fGvc8FbGgGLWxV+wch072QuMMsq7J7d03OMLyStFeMBJdQM+st4HB8ZYktKfxVCfG7Knb5kuzcKH5iavJfshFsq5UGi9zw7dQYiXqkdQxCUASRV04Bj1uX/dv5pFV6qYsYPagDZ+XO9ONWxScKDFtqMeEj8wA5v9dPFs9PE44i6488kLppnbNsvymG9IW0O91calgPBWBNInQ9mTMuvn6vZMhZn1Spi3Ss+SAnRliI1o8wFlH/vY2qkdWtMEdjzgVEW+8dWo1Wf8Bp4kQwih+sYrEItdvKL+zyhwmOaR3tg/EHzyxx5/0NlMUn9wzcVIFJIUqI70Mr9nDT6bklaEWSdPFVs8FQs5w==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
