---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgA7rUkNBK3luV/B0KdBQE8fuM6vHeQ8HAQXBNEMR6P9EBcx0amnUuWiGnGWoVo1r7jjeoCKz15uAMNcR6iCb/7WUWDfj4fy0Vwxop6TwgHZC6ztIZ9Ybt+PMTI6OG5Wl3A63GURYBG+aksJQd8NOxAwA9izrxwgSg1mcz3FfU94gR0xvoMvA238EPm88E0qF/6LH7hMKLCdpchXoUSbsQf4NkDz+99uM4rJtdEZZd9X+7Ac88h/WFiT/25cKJdQ+algcP4eaQlvIPnpP5LLi9HsK9mwPK09/oTtYfbA3Qg0DwkjFHiHSKL9DdODa2f9cC7L6kESnHseI6e5ylBprYhNnuTVU7m/DK6mcLCRbKjTU6/ghyE/BRZBri8JYG1hSesR1agOJcJphQL+po558wBq688/S61XbgOaqiVPcgTzMG3o/HcQ57vnA6TFsveOtOwixE1XqBfkUrebkGL1uuN4IqAqc5TX/Db06cChE5JQkH4n7vrFGg1XMe0RsOs59Fy8GqNDhdcFUOjbX2N65h8PUctuqhHpqApTtp9NXEFAfS9TCOdEx/5jz9FUpccOiRjpQCJzCWKjUHnDSRtxNVbRdQmV+cmN6mZs9P0FNETrKM9MoYwn3TUjL1QqAQ3ySmaaKxD76cFRW0H1WlOeCDppn63adeAGMgJ/wvzGCu5b4aippoqyj5owm4wbcABJTFhxc3IUuSWiBXn6VuIbeUeC5iPGe99vEjKo2rTTdQNGzw==
    username: AgCEoZlXBGTAZJw9gZWwgjrUuBtwid+TtRw+hTc2LKZKHSyubC2e/HuW3AQvaXMcZ3CRgo7XSq8NVnbYZkOu8BOgp4LNVCsrgTNX7sW3a2Lg18A89NjIaAn5WRAvQzW4TvhMHprhznDbGfHwxOWfaN6hh2sCsf8sxu2nntFQemb+eTliBNLjrFrayzvI91Lw+Vrelu1UUqzRt7jpMFSOI8iFBCTiRbquesTYMYErjMxUQyqEh+mJfffEAbvpJ5rUkj/EnGEJ5Ew023RmBqiS0J8nQi+9AZf+kD8Amjt4SPM5bQJI0ZwTGjRf7fctFUbtRlxFTwXg/Drzf/Vpyuy3fGTGY6XWbyKKuWtyIP2i8tpyTNNYvi7vEq5we1rC26hyYEdsE1aWtMZ7mEkAF/MDyMT50Vy3hjhmi8F72EXoPEJGIaE+32osLxR8ixrBTGSWq2150GFhvQzkjdxIJLfPPzpOg8hsJEx6xTn9YoEABC8at0HGQfNzCPD9L9GmvxCCWSElRMzLr3rf0MafDjhtgyxSsiWPU8FbdMpYVrblONfrhbXC46U1wfMZtNw6lVQfMZkOlwpWNfjnx8vovlOcPM02YnH9Ya2sOQRcvE27y+R4xZV4/4b7f8xol1NCoBvE74DmvKvwrqdsaa6Aq9wdm73z+UOw1FBY3+hnSi9rPSLVGvcO/7JOZ7Ec24ojn6VS0YZ3KeS0qCUv0waXSF4vko52rtWb
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
