---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgA1d517CsHBUp0+WfgwH22jG4iqwZJKBVIFeCZwRnt1QGjacIcQ24hvjgRyzkEVkxTcOJDosbXf7RMZwBMZbDNAdDzDcrK+GChqXlmIRtuIfeSIhfBfRsydw8s6BqEfPmdSXH57lNPdOb3fB8Zore7FDSU9uLuXanMu9kAJVhnoT8wlNmcp+GSC8H8nVchEHhPPIaAT4cwUaILLqmdlbqUWq9YTx95fTEagVDk3qmcHvsZRCjmnt5pdGvB2Bmnf1nkUWdDQeRP0fMmALH28pW8WBW8mN48IbUnpkmZXiQdb3+9/o5tIUhl1jmcHwh4vTHS173GNFycZ5R8XUyoIvXvgrB0s8kTQtbHSiZ6oqplnThB6ZBO/FJbHIeBt3vRtE32zStiB+u1aSpJqFEtp+eLiiOEpQvJsjCypoevxrH1G8QJn33QryAq2+RCJYMUKupT7KlGgfNQzABSCbLZka5GXo0mxTDI801qEwkdsBdEpTq9EKmTpHBTwRsULAgZu2zi9QxkFbQ2j8kXdALKNnoQYIMM6MO0JeJsVh/6bjmKISfWCBnaekivesz7EWCfhIp6srvJyC2DLl/xPq79dxrvB34woUAcAASBu7KuEtWPKlsRnn007sAJ8izezk2yg54UdtXdV9GBx0GhPDINrcDC/EHcQFCsxByCeOoijy7tln4lVWL78a3VKQNJRzRHoRb5r3wieI0n2wu0Vo0vZ4gYgDQrz2Z0zPKRMPordYMdzZmsIMqaFWCXv+R0gtRk8XCut7/CC+P74JFUJveRQ9W0pOanXrgHx/R0T+rI3XjPTFwY5avB6Et3NNwpzoaHuLbS+7QjaHEx91W95ypabkV+y6Uf2Qy0dR2u+z+BStQvhU+q11h/3Ks0DVoYQCupZBshFb6UtDG18+iS+iXFB86E7E+kVXn2blSBUUaB1k4FhytV6XDPFaldHGg==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
