---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCQml2iZulDmWLM1sVrZiz/soQ0vEVmEAF2BLXs59hCZxlhe36VI4c5lsuNOSusq/S+NDwXa7zSlEdHxPzRAFylZYJ8KjE8bpFY0ZNpzfO4gBfRT9s2ngKtMqru+IzSpU0jWqO6BvmuJmoPv3HyUpeat9HijOkhHb1RyEAn519HmZBZq5wvIkt3JfoaYxB7oi5Q0LOdvEjnjZYd67M4/OZ8bxhAyiqNUqM1YuKjWRiGqrqgKb7F+Gf3b5aOzmklSCfVBhv4pmTCN4PXOrGTYvUtcTAM0ZRJt3We2EHE+ODdqrxQH2V2KWhBD6dTePo+MJFmGdSazqcwhUO2t6C8xhssShYtWeMvCP9sZmeDlvdD6NS6tMq8GiwP8hEKny0f9wIfLmcTB6cLiduA2f8by60+uwut2MDq3c+JK9Vd1RbhJ25I7qzxc7SnXd6WSNdwbDV7RhZS2Gcgny2pDQg3tVGV2PxP1u7fnnv1NBdwSoOF3plG/Uo61ot/3K52/9eX7CgB53yyj6WCKOlYSQxX+yBPjMUwl8oQnFlDKEee2U6jctV+BTxTz+xa5GktyRut7HcFKd9QJsybdhSv7S7w5M3fwGDL3Ehfm756aUogT9UyMXE9R/FZZrBNDqtoE4gVf6h3l9Aoxbk8lkqqCFkHoXgf6qrO9PvT+vAFq0dNmFHp/njaTwP66wXWq5WCJna5jllyhqvf5SABkLx0iPSP6DzYUHIEpAGq8WXxVb2p6k9n2g==
    username: AgBsZAhzjLwacQCf2IA2wVn1E09w17kUXeIvUJlG6p9B6wqcTFpd2A7wpeNlkt5J8Qex5SC009XuYWP38iQqkKIT8NB8euotEX2TCnamchWr7kWqrjmwk32CUukWDOYGIVMLij5Hh4Nq8GwPgWuQE/m1uc132QBfs9XCVbU0HyU2yyOzn4Dvz7/bjYxO/TGWBCIK9B+cB2YOidzd3tDozYaICK56yYD3Gwa5cvivca3Mq3a5bqok8NZj4Z/JHQvnUSukiS/CsdKeCaSZEB2LXm0d3NPvxf5lhDvuKXpA1daw+XEWpqhrUuyOdJBK8bAj0qpx6QH2QgSbIq0uU9K0SgMAhq6bttdFGabhTBcPB5/SqkwOjuVKaJNFOStif+AVGnqa0KwVrlvHX82gta2B1rYD6NmNwLed9/3yAIC7MO/pJhlHXw+rVWR4FclWkiVb0VYzOaNstEUDi0BtTkRGmSOvHOE6s8WO2erOlYWZdEfHdc53BY3fmrdUYUhWsQwIekVfCdcNwyBqTQhuOIAyCOf0F/KoF8SNlUhNmzNfkmwldbp/5e1BYPACIrxmcFv5TXv0lW2rbSicq1xPsqTq+Z7gEqtLCCVF8bt5CZ+rBc6WL3eF7VkPERoV+3ZVA+sIA5pa/urpsLufVha/7JYxlMZ6F3ySdBs0d5qUM1AFLxBmNCrPDqoFSz5kwniqTIiONNaS5mlSqowAA+z+wPYf1ck9DxmK
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
