---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCFKJArylmyx0mNUrFu94BmCr/hn/xJb+7eAWXvIwhQImwug7cfzxhDFk7xjenpF/02ATWPdPsk89xYU5WLMrUCxzYUSined1gDL4/hpzXHKPXzgaYRL+o4gWVWc+rLwqvXLMZ5rTZBYZlhD6reGFO+ZhwW79KpP0fmYT5XtEA9+daY1Sl/kVO5MTg69YLsg1j+mlI91TpNtAOnmlasflkiMCaWxy8XI4VaALEX/dA7/NBA3ip9mh49RR9kKP62UdBz7Sla6WpN3SfpoXO7wSrSKA61oK+C/t6qcAmDpDiFKwJXtWZiJbIBMqmhe6Ix7wvxihAPVIAQ6nBsdc/tjW4pMqf1poG10Qr0eGLjZOfRrzN07huaJmesOI1F293MSr4uRYStP3sTPMtOH4jjZhrd5hgGrJEW+ctgOPEfhyejWZAOnWWza4eBJ0H5cPgzHCj7/SPEAyZzHOrTAqrVEgQak/4oU6DaMDBZWRR2XP2GIjauKBPfv8zwf4eSLmxpMRvgU0ckSgk+YCb5y4YlobVgaBJRaEqYkV2cdXpHCdJfqy2OWFzUNajMF9EjDeHRFH0VCV9/5zkYdwcLaEIq2lLcBnnE3kOqaPMTmEv7vo8+kIslERDaMT4MPKcLGcpSvppeJW9za/SduaxBBfUfrmntOhBBSXKZNdniH69M5jaZDjl1tNBsI8JF6HL1VwbwkIvk136h+3RDcGf98C16jn7FGQj7WJTc137L2YX66uOkfLHtQZrgPhwkGiUXvmKZHExLX7wnS4+UknRcYQeIQBYM2ENYfBESNMlOGHfecfwrSaSqDlzukQ40dCc2mG8PwJp3IYkbMgK8UvCmWwUPtd0/GIFHCqP4RPzByqs9M+IJ32NHAbQnG7gwnXOo0R/iqrZBww+z5fX08nACXjA+gTDU4Ada8XKHpCGPSIVVlORdQy1DNQ7VZVzipw==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
