---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAh9X1h4QPMODdAsA4Ot0quHQTO3UwAKHMX3Mqdj9RO+d1J3TVaWwFgSsMGGQooDdDesHtaohmQh5DL0vam4UEfzW8PI18kcSUbvPs6+lzC+g3ofNPDz8WJH4sSiNQKfBMBGG85D696COnJZvNtCUdjfuJ0WRzNh9gc0PAjO26JfmgtNwPm988BjsRzIehMS/1XOkakiASRyCs0PS6tJ97YaQArK/nOe0oS/037F/nkPz926xUEASvK1czrvbe9qJpm+7Lp0vtG9wbZ39yjWXZzmns/J+KhX6kFxPgU1wFrvkKFmf2T7i0UEyx5QQZ9NI1bVES0FTFfUAQgO6wqM91Dyl21A327ACBWO17/6f/ZEBS6R/ORGMvXoO3uOkhN2xibwYMXJz0IMty/pa737UU5223Upb3qPl+/+Em9nMwrhXv9kocDOZdvssyTWxiJOl7HBdw4ieHUvcbf8d1j5hpYz2WXQRIZsTmqME2pqjb7ITLjscZTbFfuFyZrR1NwstBSfYeD8II3cZs/OWnYyijPy65CiL6fBc4z8ThFCzrhRGwc3EDSitG4PTTP29UNGM6ferpbUjbau/KV/BF648yC84JLqGeY/1Vc13dkI9dljZF1T58FL9hQu79gjDkTVkeI9k9rs/SIz31WyTVKgQGPHsjbC/hzAztRwOfeZmmA0PhDb4XGrE01dOtUhZSh+uLviNH3LCxtbSGCFArVjv2MvrulQhP6qhKPxZxZdpYXtA==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
