---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBh92su2D4cX62KZp2n/RulCHYzzajHVq1TfT7ZwJH7fIXpxi7FdGUyC8NHtKYSB4LMFGmp5JA9+P9Ox2VtcqMcId8gH21MRNH1f4fUZth7kWoFFvWjE3Lz4FaXbFIqXFPV2MWFjzSR7JyBsja6gnRtSR0q9OkB1R8w6Aj5SX263MMU1BEqiYHkfWnJ5j//OUEYViLI1c1U/qaBwQhbupNr8zU/MxySu5HEKFFRuhYUh9JzNEV3NeHBkc6y7AqBC3fVdyGE3/aiGoB2zYItPg6VXnjSsLTnMPwO1MUClCuBafkhFIYeW2D8YqsaOxUitugnKzEbWQ7f3fC/5rxdhlpO6/nyoyXx3uLM8W0xjZW02DOv0iNAx5pd9xhlikvuoXDAWR9TRJpLTwZu8P4ZI4z9t4+sHSYw7cK/7hq5Z77qSztF8bn3VNyusKlWE4/srREwfZPEZhWlPC2+I7j21U1ngVgzfcoQH2y2Wdk7+GGyfei/BU9VjxoLEWsJH2y2hlcWYXLcHOn8z2ElY+KW4Let/5uHf5/s9dOP5Tq0iFH2tJwmB3M3CjEJxL8mhZwAC0dk5bFtSk0+D0cr2v7rZGACNlb5lTlCr0ENfBiUK3N5RZq0OBasFU2PoXtVrk1FHhEv9s8hoSdMHFvX7+4GPfqsjvPCZc7dTC32M5B0ks+OeBPVJMdl0z3xgGI1Z8yaz/7jEd8fRPTNTGNTsOweKXXavHPqslNiqr+HJ6iT7xwkpA==
    username: AgA03ofaR1li7pA26pCcXcuW6oPfiGi5Frl/4cvCVyXvfAQISkgKmg82OwXC+ZO4rF4rLY66zPpOJ/V8ftEzvSj24aXrUmntQWGJaUrC2tX78Ll9O73uJyWoafPhmYOvKCRQtof84g2qAhv+jsCUdjFOXfsrWhCnv4dwk6I1GWSb3R72iM/AbxfPX8X39Tfe3eqdWIP9DHynYNsoEE1t88y9Hbky3zC7fZv7s55Kobhui2LldjiL2X6ptYt2o/qsWBRy8cMpmZUePvzgxkKT0boKJimX/g6MSBT48gNLdrktrkNMAQm3dWAuJ52aBAV3KyesUELpMq6c7reKQeB07eLBbhO4V0mulIisE76xxoC3YMoiMEIS4ro/gqVlNtGHkuOKSCGAIO41tvANZ1XSF020r/D55nlR6DEr2E01ZdxCdO2mrN2ko5lpqSA7TG4gq2TD9xDdtfSbWWGGASHyHwXevun1Gp8C6Q3WVZ90PlqTTcIGXyhCw3IRkf4tsOI8cVwUsQGSd2xaO9vGOJA/4SVxkcNBJwewY3wRDHz3cCLHCJbB5GSP4fTHROT3fqodHuk3T+UShqUkGas81+YrQCKgw7KFQ7rRQzvH0+aeSq3Elv6iDJHvw4tPkH7NpA8H/FQk/Uatc1VzzQ9U41E7kKoiGO/UYqBPURSC9EI83W59CSy/0zI+7SIo4PA9SMdw+RF9QIwETRitOvCWpl3KTvzelv8M
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
