---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCa7lmheiXLhtx7dNd9uOparqiC6bkFBQVgP2/tD3JDUEIffzhruQmnFJWPv4iJf7dw40KDjSuAARnmT4Z1X6lTGavacSacci2Cpxj5+l5KXsSo5deWWO7J3VdrVKH/oNbzlxLcDv3y9rArw2N4snToq+AWy0O+Roq1Q30pVpQxz03ML3V/XWcZmbVcSjp8pbPsRTSELVAdt+X8VWlKsinIigiIcihAri8huJ+ZanQgQApoCqlFuZQib1WrYlDhPSf4Hqq1mLf/gkwyVfEeO9+IqNyO2goS2ynEQku46ZEqwLtUFKrRRIPB4ucahFvyRj51NzfRN08fEkEs9cZhXyqpu7VMlv8uA/3n2MDvDIv6gp6kIroOeIbtZLqS414mdL8m2yr4iWq9MuEQaZXNc5cR0ty69NITZGfqFvwvo5DrNI2BuCLSyS9nXVVNtwJ1e4tVPtaPazqF/kLCPdTnr1aubviP9hvkMIQ/HdmDU0h+8zlgugdrRgPVm3ZDtCD+lcvdVtOB4b37ncJkAAnXRSJUtmWQh85R7kr/HPSQTPWuh3HWSb4h/hIsK7u+vfFIP1WC+G4OjYqcfsE0cQJF7bWAQyP/EOrSvtMjzkd0s0etBuyzVcfKwpdVuLC2GgJnAY169hq6bdnQm4I5ehb3CV3F2X6WBJe7Ujn7rXf87FK3YNxtP8bb1o8hsIEdGtLw7fbZhdTKf9mKaV3tuhlZg3G+mvtyoJlNHc0g3CxBFlhNIYdBeszUIZerug/VcMox6T/pyS2CRUnnYt3zSmArqPqTqwrWnqV2/pH9wsgDDELprE7wKmcVVufjupbywtM9z/Hf9ujt4MRMOmDgFx9kNr7xUufH8ZJ7TB+D49mZDUttiCnBE4Gvco6SIZGs/+b/BezShV41PYM0c7hoNZpHP6MwM0diuc5ux9b8DlzyMfJMi5KGgxyF2v7E3A==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
