---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAdBqjt6k/Cq8k7W1qA/eUyF2cIiFKP9YMPHzbNFmJzNcTSaIyDf1xpphLeLpJ6R2xbxgeDyUIdi1OJ/z/IiQke97V3XMVXIBdtxwjLQKJ1j8rldk4CKdMzXVHnDYkl4cv68ueWdD0+yCUINkp890Xe1pXcaP/M4wAhoHoYqmiLj8k6u77ysOb28HmQtcrOLs4gaoG7av3pNorDjElnKGQx81yM+zT34lmDYs9Rcs/JgLlNL1+tDB9u3nxlQGPfW/2hKu8gDIczDkFTFXf5VJ9SjOYs/pJ4DZFmL/uMamiU6Iyy/is5r1sWefC6c4tnZD2CUFBkeLB6MZvrEz2zy6qEm2jN9zz/Y89BeVXrtwCUA1Gae5luynEFgdC0bPbPpNLCbLpSfzyaEc3En9wpqX3XU7rDIRQ2HfyEFl4fJJa5SE3Xo41iMI33gFnzq+CoHYqZWbluySeYtvJPK5HfA7rsLoo58yDRTgsFFMPWDpX09hOtK+yWXxqj9bV2bjsK65CDBNxvK5Fddrut1YdjISLdssi8O2ktpRqc+ja+ivGhV0Qty7UIhRmqs6b/XMg3XaIbJHhrXlggcXmP6jw7MWQ82CYQsBW61aiFX28b7SkDMbEYMFX7Eqm0wpCVgazzZOwyjz71aBkrcnJA2S234/J9mvfOiJHA3oqoXTfq99UtD+Dm+VTMRZbS5Na5qAb8tHEyuQed0bnlnsEOWJqeBOvhxHXrumTNRQnA/SAPdDAV2g==
    username: AgBwlXE35UDgyhmGad5AUwQPHYDkTjflcPzwq8JXRXEMcUC2/xqAKvXjkrQmBODgC4szxwIz1I+NKs2YkWcuSqHnuqEDX5l46jqo/pItDm4cRBhO1vflOQ25bpIDFwP2wFay0Gntc0dI/bxWe/TW7+EBfVPVAU1Zj675JYJ8ymT4YwYb2i+f/w3aze3XU7WnEhL52yPqkVFrXbw0rGOq+XitEWJacZR6iK4vieTxmVHjjW71KQyLK+ae29P1QRP1gtuHGz9cVlUvOebpUnlp5S80oDcaffo1pIiZdQqKlplYAshcvPEEJ+WJCJOzjxQuXUd1sJSs5xbp4NIbk0nKCGvBsnHPyg6KUD0WLhwCjxjPNbLeLiz471zCAI/nfZnmMS0laLO5CUNvWw02raZ08Ou9j/gl2i4lkZS/SXke3eDXqMpd3R0ne/vDmyd5eYHqEWLjsnJ02aiHurfQTZAUruY6oYS/F0zu1pA2/XuWFCcZL/JvhtAH9CZut86FYknUCluQjAHKEa6KRHVZIJt8xtg4tnfQnCeQtqouEErmfh1e19fw9mDWVaoc6MMPWbkSWpEF5b7JuHGVSWMcQzUWpGkZHAFytl7cSCdtEaY+3Tj5Wq5G2LlP7IAH0tZQFLfxeKJS4zhY1lJuHueU2zx/+spkSR7kftAFFDrs/KpLZuIumpdamF3iOcIG9XVDTvZQ7CMrNwMfTwFsAxERfXKYqbBGS/Z55lw9Zw8=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
