---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCMV8YuwsmJUKxGOC8V12j6DjObGZfZrU1GRg33vhNE2gmzgFMTe6z4LaBc1phX6m3yyNYroNqqVduh9y5jtCAeb0OqVxXRJMYaPgbt90UlhEmeiuydelk/ZxTAffJwe9IzQubA23H1EreNnS+sTsoR/a76m4P83URNV575hoONJVRROhoWG2aM5vOGY+Y5A3GmXR9y5wIijnTH9MEAAfRpCTmLm/03LMv1tnwb2aoUmo615ysgoOPb3bpEWEdUvqOVW7dM2jGhARV2TDKB8bjXtyvV8I3GGWFZZ+LGCFplkfgbkiM0q74e5bGLDtMFhB7kccqA4eHORwOORM1aDj3J+Nhjkv0a5jSTVqfSb2XOqEco8/bJp2fvMboLXCqFPuEKtIuJjhemyDLFd1T624hrp7wkgbRspLU844T1WjyB9b41jSHzvzP5w7sRXBQwPhbMP5KzITdGkI44BPeA9posi6RKYOkFbkKbtcEmOqgBVNEvvRSxaLvco+lBdii12mWd3Zu4notVAByF4rOxkVWyjU4wjx0JHLlcUHou0Ig0Nv6iEMbt0X945Ow7oEHRb+ypY7aWVmQ9I9j9X8UpjNdudt67VsPZiUX+BGFHgbzh+hzVNEsO0PbkVUo5ac6agUJpKldrTFGGVMrC0W9eEB6Khm2lIZw5JDNM8QlP9fklzt5blY/9TA1Jxeg52zNliASPBHpIC5F/At+qPOzU6A602k2R2WKpsHBjgPRXIDODqA==
    username: AgCciEg28nXtaLAf3sSTGm+3vXBSyTmgvsfs5IT9JDe4LXDnPtiruRJxTfeRbb5cLTGFqzRnSa573pKOZ4VdGq7Pw94nAwpvJGE3wqjr78X0xofWcxHgFZVLKrYfzEgQEsx3+2ViCwYT+Q7pvKCZALcwKFrQKH54ebkV3dNO4O9CTPShOxkpsA/CH79KaSqGAmy9bcO4nYVgG3mBXJgygWc8s04JJq0sWHpTq/27kFwP8FQL+13l2BwTrSqfmYK/GtsobUuABtvBDuW11j/LHjMC5bWj04x2llO73yXrudmi4wVkTPQtIlGRsxGkJ/uzr525ApUc+8Ib9mVV0/wdiGMRwEXXkixrfTcZCeP2KBydMQNXd8XwKOM1XUNY+bEQrzICDhH60yWnCKqqKvNbxsH/FmhiDkXSvbGe43nwrVAwurSf4oME5jfuaJWKpZN2U+o2yF7I7T/DHAaljpTje8URLjuiMXbgtBMkSRvtlXSDp/xds1to9Bm3UhdUtwIbHdC1+N2PA1xUgKIs5jTx9V3MsYfeMVgmf3F79/LvvPlaIoIGN4o0UAJlXutFPp5kaPFK8khcakB6zGh2qLVx2FpA/6iLGKNL54l7vLFGn5LyA6d4JEYEvo5x/kuQ7WVaVMLiTLLFWJ2b75n1KVfcZcM6VDCe00T9+kAjUk4oHl6hVDKfPxrAUO+o1UxqoiXruC3F4MkhoR/sZCE+rZIglHK6oAVzWDNMFtrxkw1OuA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
