---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgDDjRQ+o/IjCuMftaz1buYerQ17x6FXfoFczD/jIbEcpk9ucXNdMs2zgAM/R0HQbqzJc+wj8MAhZcvldxhuEonnwtXlGcdx+zpu/XZVDPnomicYuFc/OHj7GcDBTznU47Pm0Fdh1UwoExF2sSjB38/tiVEdh/Rf6shuuXm/tBIRvxSiOfGWowgjk2DCozrxbOu0kyNo9fZrTbsN9HWowDY9k87fHX4MtbpJ7JRzMX6R2SrsW8Z4t7bZNHlUgcKltFC524o1SOXHj5PN6FuIldDa6qf7f7Bgs4iU/TW6EpxVZZD56oSOLcDi+qCboIq/tWBKLklIO8ym3V8OcqJAmAx+ubqkE3pKibF6njUm0odOdfFUjg9P6lGNU1jxnt5fpFunUU3t+pQvj0EDneUzEr/tOfVtkBi7niWdhm5UTqFO2zw9B1sPVH9o6ISAoxw8CGa4DM7C/p6H5MYiizMzeJiyicUTEgmdP9HyrV3orRhQQaTuoIz/aA/xnOI7V5vzzQZCmGMkYUKPa99riRT/LRU46EIjI2PeZE9QwXBykHVuLtkU8oOC4JpfWbHLm+XWoXRGKFCS0FZ4vcE8ArYha0ahIo7fZGKQfptWZtk/beoAbY1EHzN04ieS56O/qae6+21Q6WWKBTwMmhrop5eFb6x7AB+9cnbBl8u7E0dxdXBzkAECGjSUXMI6/bm6dUOuiuZg4GUMElOqOY0flrK1iI+b1BM6hL4KZtbqmHAo2UhKMg==
    username: AgC4m5pXOFZ3oRYMl6K2BvAH9CGvtToBPiK4jz5Lrmbp7t6/rF4j1ALWuSambcLHI823NoSc58gQY9aA8xB0ajmZ2IXE4pn28fQcKd4JUT3ZVGOPevvf4tlpnf0VFFxo8MOMUN1LIjbmiY1OhhNKFKlpvNdfRvCJ6J6i3R0jOBkuV+vAr0i7aFLFf34vmUpBJUaniVRhmiLhrs0NkMYdYQg9IDb1/UAIlxaLp7b2Nvzx9uQn75y6Oq8jDkh/vlxS8PkF9WMo894F+JEJv3hP0+YUhWb4FWxpxvQukAzkcGt+Izij+g6WZVpy1ePnAd5dsx2NwxyHmnQDrIAQGfoMFejgAvwyfDJbCkQ9EdIQMRTc4hf6aJpoWadsN46n33EXli+Th0yXlEttvr8ZzJxAqmHppr1QzH0OcKxlnqEB2m2LBEq3sd113E5lWHLXp3YLEMvmoH1PaRxi5CWerkWiA425YVsrYm6XiaFa/vnJslJ0q4In8Blj8npFbsy1EfaaY4K+BjH9o6si7PobE/wMyajERDkO+r3MUsHhzJLxdQfeQ+MYj+utDQ20Y7lXdjF0slidIlKM1xv3pIagCqoFdwLBW26beHGHSGpuzu1FZ6KZldyT6ILpdhRcYiOyrHErjrME2GdzUQsbnT3PRTv75MzwgwtDq1EuhDSP+UoKH7IBXfKy3ognAomKgkcLiwwY5yRfMzehyE1Ev5rlb2DtgQOA37JdOO94bcnATdA5iA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
