---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCLBqZfdjBUkv5MzS2K2m3SxWK1UjaieXW8A9a9ja1o/6oV2w6jTGORJehrxNqwdkuXnaPCmVKbqVYjitahd9JZzCGZVjDWG0hBBrrC7hlqcxOewy8Zo5DNiJNv69syYs7yYebiNGk6DkDH209Q/fCs7ayVwxMFCPsOfsHFc2+adJ5vagJI1S+mVR5k7tQX1Q0GLno8Nfs9x+Gxh5eJh/D8kFF0wsjdUNtg9BNxQNqKVzb19a/XbZEPleV2QHkqwRKrvHFUdfm+SRnPuGVgHjuQ5EF6teEDvF85Ede+9YcghZF+pGhfG1OFV6OB/IUqwLqf0+v+M/p6Tc/PwtPTNHtiWFZ6YGoElz7JMwHwCCD8KjlSYmiLO4ulEEMlBcsvM7T6vU7AWJDzCSbEPJbBIsjqnoGHA+e7Q+jIAVjfCTESp1zUHN1oVGjIFr7Tmn5yf3hdo7fZF3xf0cuQgsTka8lY+WWIP8l53rv1BzGVK2QVgrHCwALdZBKBsUBsJq42o4MhXy1wkNHTDLk3+IBcWaTX4csYoH7sdkVr+HOLN8AFcBlO7k373nF0P+RuCLL+r0Q2+ddjmpezvyu5UKcXBrlsQJNz8qIFrvpkS0dc/3dlJ4a3vNgjursLgv89riSINVOm6nH5jyai55X9Jz/WE+tQfXEFqbdawg3tk3P+jUVwKWEO+4umVnPtkSPYKYhvNxOy+3wcKcmrkoiQQV0Khzt8tysTgL+cQjq84fxSqTzs0A==
    username: AgA7Kx30EQoOa8+dVyYsld+ZBrWAC4rCpzQtCvS1/6jGCfIurW6gKJ/rf5zasHETiFqDNBLPf8fwkMUykcVtsetU5Q/GZy+gQaTdoFIW0/BCPqlkKg3MLmKzDeXIs6+oCmjMxdhjpduD9yvrAW2lY1+fjFnBvfkjG1ESbcx4IW1xg5PMO56L5zequWySnNqoyTwVZA1+48ZB7iBDdESnadM7RA2jPbilKkuKuPKairtDZTUXuAH2HY//Y2MEcQ+LCBHCE1W53Cs6nzs2L7tj2iUypIh0eufR412wSqhsS2z39VBnp+UltKdqNxRr8k77pTbJtsrTLTAZ2+z+eAJcE9lkFDOvgRI7EpG+BhjVP4L/XpSQH3ajXaeVXHjyTxxA4IoczrDfGj8gpIfDlOFRCZxrWbXt6OfHYL6xMeMXcEBYTP5uszll0YuQLavYnkjEvxEQD8qDAdOL5kj56JqDAIB66s9ZfN/G48f/57bAwxIitPF1JJ59JIq/GTEukkCanROZLgTRnHgFrjliu5hUQqe+uISPvb9RZIdOTxTHBL8SzaKyx2oMzVfx9tcPk/7ZOvn9ZWs7Yl+knqa6gzvPAaUDRKOsr/H/TljixJ/e1wi31o6QYvY1M58F9Cqtri2cEM6bnh4gxdUw93RLUb2qfbKJZ+3mQbfmR/Z+tULZAm/t5AFInqvEUBYyZ0vdzBBsnPc586Nefw1T+iYMq0aZkYvM8BwY9xSujv0=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
