---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAhFv2X+hXklBrelEvl5ANqvNidw1zMBLWAueKOZ990eJ+JFUzYppxietEpOeNHWWoUaj6kIF35ejtCvgUXFldhUKfceC5b6roClhzK17iFoi2oRGCipzzWJXM2Ct0inyYzQcJS6RwE2aAkwDHrfaaXU6S1ovBkLYPY1SYWkzt3FHNqixHCyXJvXm9OaSsm+yASkiwcIsd0B+QTisUJR2TniXjIuVfC2V5k0pALyYjmSYHX4pXiFHL3GwtAA24yKC6h7kjQ+Z84wJdZW6VfrrSbOFZebDsKW396P+H0y107+TlIbYKVeuE/GMAAGxuRsi2A0KcEzjdzd+zUfO/vgGbqrqmYSH+9/ML8kFj9clLxrl0F9inRwGNtdC2v6ZbKSvqIhPp3glBaROtc7/lopwpfEqyYmoNcfe1Vgqp7QC+/A94KSyvgZSszhc5KSm18kWjdh1+MX8cqsyMgY/X2IAZciYRmndt91ucmDBeXxyAIZnJ5LXVWih/3JBJLChs/2ABHzaH0Xm082eFdMIfWm8vBfuBc6bm9h7OXMU3bTgeT20e+WL2YVdBeVwsUMTi8EI3OdmrZfJ5mcL4X3A77fCm3VINKl36IfovM/mNaqpS9YwNvsbmlMIRTJFs5lx767LGKcDz03BvuuSG35Clj5yNuGFUDSvWTISqgzUKVUrk8ZA3Trm8g5Ot6CgOqkzijrcMkniRTiFzqRjdbjBWdsCtBverVlRdkDtOYBIjanydoHA==
    username: AgAlUtik9K3CJ9Uiib4bSja8qwyXnosFJAuUL7ccqyTS3GEQcHmHDzh2BYv+dZqMadUeZa/FmLyCeE607U3wfM4HraTxHsoNEYdQ6IS1wJ1pl1Bc9g39KsnhwX2aBltjve7UbOa7iaMY5SEiff0T6AIBr1LUdzWsu14zcrO6O/yNSAaLOX/2qbEQ0nF6yORELFCB6TwxsvjQ8wNF+iooipH1QqagNMpOEysXWaeOeHj5SWOOB2qcpw+P+zFzUv6MFad4wXHSTFceoAampZExnabn5jLc9DAUquOF3cIEuBid/W2pVH8phsaZvTmozs1h/uE5AekWxQvZD2G1qgj9ulHf4fF2kzHgbtwFTHMH/IfU32NTGCiMkAxj00vDEzZuBl357lhgT7NeQgVxOohaffxv2j0h4KN5benzo57cUmvlCldhYTLigjKsInEMMHCApRvJ6Qg8n1YDy1bsyuGmB/cynUA0FG37ftZgTcsU95sfUmUEH83274qSxiBd16z0hTd6vvWaDAMMmoPXm+djEaGur/sTGkTtRQIQTvys61LbKBB9fxc4BS+xwhd5zuiG7RVoNu64IHKZRa2MarCD4V44dhDR8eRDGzxqC0/CWWTKXYDBWNtpngpCB9X4wmZDc+Dgh9QkS2lmRiTH5ggixlDmgEA3B4FdWmUN3A9GAZbF+oxCc3VaDePw0VGPCj5b6XkB1igziASjcZ7fVAM9W2IuvBmo4ezPhBm3LaBolQ==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
