---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCDcIASykSAuUgfuzVE+mVGj+Gl1GXWaOXmi996f5SrxdjxXNDtyz03LQgEoyzs0wow8cFySZcxWmcuCG6BnSlU7Pm43ejUD1MG4+xxuhQs6r048cejtN+ueyWtCLuN4YbM/WCnVdH1wqlyua2bNHXcCBrZX5vYGUdBZ0aip/j6R01VbvkSpxZvrcJ+k36eD9RIrQ5ehKrw+2vSD2psBiacM1JU7gEBjrTOxB0APwvPYAZh1taojV2SEoxpH3h4gnWk35JM2QtXeDD1v31WtNtODRQRX7blK+GIJUEoA1Bv5L0VsFGza5D2uWH62E08Oo8wFJFup8kJmmyXcEhdOKB8f0G8JgehvuoPKn48AMxAv4LgmW0pdm7xttTeNBTcH2EnEulYq1xYUhA4R3NpeUqYyJ3DcCdrcrrHSuop6AMIKTIRlj3uc+zHla5akg/NcLG4k/CdH5M/hnLhttEBDz903wgqhKEJJOISMuFMFNsIB+mX4xVnHF3oetyy5u+oCK1u9/B8O5rohBCVWd7r9U857OUf2eiesyDsvjLQyVC7PSiMcq6NaIMckZbSs3ZfnOlI+QlAKBWvUuDoheiI0PicjI2L6eZKtKBPmy5ef1jsShBY5gZC6Rc6b7anS7r3Zt9mmhtfWytp8pN0delGmnniNe+5nY+/J+rDTw4L6416pM7KpP3kmUW5Hmg7sDimpqQj4ZWntfJxqytXAy/o/mlCvafQwqVV6A2WAPpuRH8YsQ==
    username: AgBXlaRcdJdQOErDXciqGC+07IgWZK4i5wuFCYOiSvJo5ulXCumhLNBBswtvlzZ1A6NPMOVMTfYLtX5bVRSXP1g65SyE2TD5C8G5oeeHpJxiHeiHXon8ucvV50dM+GJ/++Prq+RcF/cBieD5uWrBHSHQA3uYfaRxVvzGyr1/y0CfOCAFW9oXX3ixgF34g01Lm0tZN6aFBUcVTK1Piiclu0rs8QMV0Ol+txn8leeJuSCFf8O9JjrQm0XxStyqSCq9bLaYlw/Ae9Aaa/swJ/B03ZJce82h8BcUGaNFIev+K+Gn42ywpvWestRLsof0O1jL3JQbI2Q+usd0vBm/zJaNp6lr0zymPjgBxZKsfYPQgu/VDec1uiRe33KEgTEqPyMzwoStmLJig9EU4qb+1eECzLkqtpOrW9aOXoNdVrRB9PbqeYfao4S6k/LCYTYg7KMCP7MQ7OUJDjjv0rvtpyThbyI7G+pMTYyUA9FEAat0SrP2BZMB5VFnQ/lF5bTJYVRAlslIacvLB3E0UrrxiJWdIYq7j7ozffpEg65LYExmCNgG+mZiUU5gJbz8SGYhi1uux/NZ9aAjJPkd9neSFg51zJNh+iA+YrLBDfewX5Vhgk7r0XGFDpfJep0jJzdL6bgCglPMAWFcF1ODevr+31+wHUwPYbJcb3wJd2dnJjk5ttXz82C76tevw70NGG3V4pcQR7D2CaZg6+sbAPxkcfdfiIX+BlwSvB183oq9iZpLJw==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
