---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBf/0pIG4yHxAn8/Fk7TAS4WTC3fIms5SUgO/JKSyGp4+Vg/YnP3TS0nB/w60FLWGXPeNzsUXtdvxhgSvz44igZxXRfzOUqJop7tPAiGEPcxvUgbe8CmPY0XaJ4DhexzDAnmmosyKSFMGw6yJLuVhgwD21fpHwVG4tiku0aMhZYaUZI8ynL5JJePd7nYnhOGxws2V2OIAGEKB6+RBaWCqvIUvYCLz8MKWcgBDH+GaMNJbjUGx2BDb/ZgDrVWV7D2+rluA79Y1uqJTkDCwrPiWCubw1Cx9Nm68QzoAKFtOJzIlVgfUTMJYPdJccPmLSasXLNGIgHrC5ysHv6fuavnrTmNW7ppHmXegfLEvrI4tCRX+tuLLJLYzT9z9u2H3DACC8zvqMO8if0HNxpt3cuzMoSFD/txx0q9RTVd/InNuM2x6sTVVTklGyYdzD+ucH7nTEhc8SZTJDrnOBJpyzNnfyumJ0SmrSoGB193N1HZ590rRWpbWlnk3aruqJbFa6pB5nibyo6pA0o1RDZcoNllzHoa2XXvpK5zPWCY3lmlWOY/CRbep6VMQkuqa5FV1EMo6Q/crRidKxikQCNRV/isz5jj9Wn95OCxTto/kMaPc1oF4j026JMkafRWZhViRfgdu7zQYUBmLrGlQpQQCj00fdEP6j65tbvs+bx9Du77xFAGY34vRqCEWGw5uw/s4n5IZnDvHBoN54WEoxXYEk8ijUuLxJAO9/R7YNiCCBFbBppgw==
    username: AgAcpK8SHPGVGrXoGgI88BnCaXH3+4zcKwfKwNmVn62XtGImTK9goHWCc7+6OBEJMiyFm7ojtaso7qESQ+1BHN6rJfTLYVBjaF8YEca9tYWvdf8VIZqoXF6Bnd1qOq3vJ5v6KUfa7R8lKI7K9DPSDus+tgSCNTanqmmNr7nWMWd4YLJIq22RjccC40YbcZ5pgE2x3oOhzKmDND+GGkyZ9aG8sfOvej4ABq1ul25OZe2tX7me5VSzgMErqNFLXBog37cxvbWoZ16whSk2HfmCrqyGTS7IcFpcpEsEzeFuo+IRGxQ+dCH0dIgKVvqzrJ9AQfFOMg4XGcH6uTMl/Sw1d2NNM+d6tU/7E97IPS5jQqiHEJbc0u/TNfTrr8IegigavW1f2ohvByQjuY6NxfKFk+bSOZARR+gSQds29fEfXTLi46Kez2LJ9v2fGgxkBsOM/hicANRWsG7jaYQ3PTckFr7R2vpJPFJ9YirSYr6o9J9ppbObq7qK+KJpZmbQSC09WUb/jmo01KjSBafgJKkgWE0e+UknYqeGUmtI/bZMkTXKRJi4rIJZR707SllBalKxqaRS1fuFLdbBNsiTsItmaxopn8FiNeVJ1VleauU0je0pDaF4jvr8HTcH6pl9b+d2HKoVWFbJE+dSYBQOWq/pPxHy96hEYC4kOoS9Azxb5czKEmeLkIQnP5VQSCDpttxLS7TkimSGmzZFuRyvO7qIbXTvrc+p
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
