---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAWNStbJT/adCBEvv2RiFCPa204GiShEMzhm/zXjDCvoqBolt6u9idACtx6zE5RDH9x0qGdJOH4Y5uRSFT0WRCNLSV0pZxefHrgFBxSXPHvfxpFyl4jg0LDcMR/B32YJpaisr+FS6k0KkXyeaa38TokvtTtdH1L10Tw++aU93Hw9Q2SuW5RWoC92sjLNY302KeCA+XSgSJUneC0eteXcrzarEwNIijuGZeHGKwqzi/wH7tYCKplgik6TW7cRotp6biQG9J3vRBnOaz8VuNLKeq8kI4fRwCZzLviWl7MoI58nvLZRQbh1/dNLzsJeSmqoqlwP9AYkNq0PUjOXlz5UdHAPQlyxri5rzEWrB9y0syHFPg3vnMbCJS63Km3hFlI1IrPmAnytVEtUd6kqxb5XA67dKbJVPf1VaZGPmacv8jYRpLFUkL09z+EciJm8s/w8TBia+/Ty/vfz4wVp992Y8Cyp4B8wGMqVjoBAGj4knkbJPRu4lx26bX5vCGBRqBOgaSSPDAvNRCxYfBbZr8nXJFJfutlfNjuRHfl8FfDYohaAhiIrfa1Y7xb4Omjj0MwnC8GIL+CK1I/qi9hBnlsGSogfXRIeFDr2tXMLeqqu04xAc5bwSXku4ZNnR1RZQmAKrjJ24OqSnAN1OkYIEmpH5Q0ipX0+lEdgE8km3XBTwLsex4QMs+ZERT0n54+dko3S538S0TA38zskv1/2uPwBzhCaUtZjl56QiexY8Nao8gd5Q==
    username: AgAO+bsz3GjBpAcWaS5NfKR1eylNwO+TFBd+WpsCaKhyd1dBg2PDcH8j9B0wKI/mewtz5uPCWHjWwi2QdjHK3x3dfSMLZD2b9Wh7UEaWlefK5G2giRGpJbeZXkfhYBBNWI7vHLRlCMpSDhXnq+VQpjIS1oQ1Hmeifsyli8KTlm7YKg3OVnEBqJ/lBsubHRE/8f7P1jkYX94ZLgqlRt3HAg8jPgONVO4iDuy/AR6yE/Xo0u2e7iWwFWyTo/+c7GraDaOETSRcR93YpLgFY0Q4EZMXN3AMWylTIK5As0JuDBpDzh4O1sdi5MN5mFVzZv8hyihWm4kjEpCjTYrnwWJ6qKVPsuonMc+/ueIR7oQX3UUPHTFUQILVf/AuRA+AwKHP4kATXKy9pB5nPC7TVbYVF2eKQpIaMYgTkhB2kRCefQHmzYoxBKIoo225G9wvHpbhbQZxCQiJzOWuneqn/ukry+T/w9NSn/iuAZaB6OibQxSPtcCK9VqOGaamk4AedjDBnFoF6/+hE3Mt+J9vyNbkLQO007af3MmIzcQHrIQHpuo2OoKuyZWkD5vyrNmZBOpCB7kq3O+FTqG18FyrQdUdliVvsfKbOstrBIouqETFTyKyl0yrecYN85zBdLRlip6mOCYLn8GqgBKQeeMQOxVbMZWhjqkFp3zRZEkBZgFKhGbwwp0udCAbJQmOhFVc4jomERDx34vFotnjma5awxs6DlTpCjwVWpj2rVc=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
