---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgB/dnH14bu3bDEOX/Klf8Zl8Djo0l+7k/MWY1yPUIU6LWEQj/4KF3AfAA8pEhyHIBrb2lrhxX+HXyaiY0KPaH8wBJGvsBlIUJ6BdtrnNMPfCH1JwaihxqM18b5HksA5pqX/XPMDIIFBfvirIzokQaYMKBbCHydxvz0T/Kh1dbK6nq5pocayo0vyZeSf1uRc+ATKY8ejQzR+ifgsA54uuJNFI9R5BK1StVs4xX1JYnx20FOKtq5bg2+xdtIIY6quN7Zw4Ujj4ddzRZHogpWMFq9LJ6tdOV7RAJhy88oAMF1nttbxmrNU6PWllTXsjb/pgDcn3Q4eJaz0027WIByukt8zRUa+Nk877mIBWOW0zHA95vkGlutoHNFS9+adJk4zlbC6ZGhLliv8AP63+om05OoUZuLeOLmGaYyuT0/Dd/a1HatuqJ0g6wocFnk+UoJUPlT7+m9xeRjFBpDxZdXFLqpDBECGYFSvjEFhm8XYPl8FpSGmE+kEPIUTRr/0uqTe0ptCv1SocF1REB5SY5Q8sczdc9Ut1u53UjWKoU8HCSkpF3h/oWDTx4nCplwD5K7rVIM9pNWVjx1S/Rkbym1zmdVFumsfleGtlfMA+mpuq7VPDYvLsq9VmhKK/Fu6VmJqR+sM7t0QsqPtr8Px2YkgSewIDRupoaKtHBw9sjVYA5FTI7tRLzxT5iSJTvBRz+BwGL8ykDebuMbBvVehiZiNvEKl+18IftC5ZKemMbfM9zkALk5K2Yxo08aKa2xWyZIRqhIHD0hcEZVplhf0ZcTpx+qWldEs7nHRJXKcq8cMwgxcgOQU9hhecTo2adun9AK9krrSbtp+xG0O1Tvn8LNcEGn3V60+bDUN9f0kPKrAg4Kwi0T+qBZGKZRXoMhH/5KeogWRQl6Vd5aC1LeoNCML1FzSA5mDAEYpnOWu4kbbaxdYzaZHOuXXFSxMKg==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/dockerconfigjson
