---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgA0FKis55pHqpvlwYKLB2cRG58KGfyS2HiOJk9sqtqi3mfEDQHMXynmMfBwvpt8r+EhvMfYuzsWPjaLlZtoLi2JieFobq5gH4f7Vb0lnRZu/WhAlmdZX1w31aryFPSRiMDVEJpkeYDtprYYdxNF38TFTDI/uwdVkv5dyIYlCXsIcCtrM4tx432He9JUrnX/DJbcYdqxE7N6Fa0Af3ES/HS7x9/fjZpJJanvAXfOsg14GHHKyOnyZAMtfqaJbmy+zK+rxGRNgnZipheOKZINGxKUvEp/ozu6pcwKszvAy8tkmxkp8yUUwM4AG2ANmX9lPhfRFchCTpmPppCAhfTJyrWh7z6MqeLxBCuMLnJOq8ddrAt25bRmPhf7ZQCtstEtrpatrCc25HhwJ5l431ofXWk1APhsD93hivUmriBqhVzgsRWtrKY1wKAXIe2nOyHpNmXF0VKS+Xvv0YL/wuzAUHTjIIKHVJSvab1I9PFrCBArT0H2ST+2Ttt49C6z8fgzXbf+Ipummp/4Kv4C8SmGjv33Ood/H3grmeEhfNeg4MnZev2PXstn4HmBYsLxRP1t5rwg4n0Ht1NMnN23ciIfC0tV7vLc41qo16KFqOlbjqSfPnydt9W4kbDGEDpIy3/v5wLwMACryT1sj6IFldxr14aA9wkjLogvU7LGAK8UUIeb+mK+SqSgjRu5i/MjNSrf925uNgTTD0BNexieAw2993P5V6xpm3zWm1vAzeIXuceFtw==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
