---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgB5k/+UeH1ALR7eOjrlRwMDc+O3oHfzx9aQkrz6BdB9q3ssAMp/5J0Sh3ReLP7r/pnhsvONmi10i46GEor0I/nLw5YdKX66YTI3F3y1xNiIlmJNl7IE9DxJ0+8atOKRNGF02t1giIunO6x83xfOZ2N6iOChyxHJrrgP7u/wZsL1KlFxFVb3qvjnZGpUQFNzoLOm2gpIxTjrVuQaC6OAYovA7xCEeH/w1LGeGGS+Zpl1d64qJx5EEPcMeakR/ZqjeH+yzqkGFN7PuX9sL7cr/cZOatUCNaI+UHVpoRxlDVilrEoqC6HXOI7Ivs/H2mSXP2kVyOa/fgzxCok75HYLb8geldr2vZw+d9QfVaTCfdKeK9mWMDiic4RUTYoRHKFFgYNKM/l/Y7aZ4zOhyX9xA8NsmbLr5qB2SfJxkHneER4uI6dEeqltbTCNdDlBKvdTyjl6PzGbvJ1q8vhqfGdAEDwwnTH/fwhh7yfcLDmpZXLhwIF0qabSSxQLHHYrBcI/eiTVZqpnG56FGUAAGwivyoWF2YnAsnDAvPyLkHonE9DbhqH4udstyw43rNDWKNxiJbTkjxrMgQ2toiEHQbRHzIjn4mBzbVl/S5N9FLaMyDxmBte9NDp2cGVIo/wK+/MdgYQmkDozmlvi6rQk4/XsxXSPqNjlyqb0SGqTnUnzd/ZsLaRBTbpwozW+1nOH+0E4GORpgProq2Fx5OHDzbc4NP3ZhmGZ8B6Ikjlbf6cDKCY7Ow==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
