---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBr6ZlH/y2Rdwt2yBwzmp3cNXqK4Bi/P2nJ2NB6ZlEww8M+FLTg47ChV5RYdb6aHtlfkFGLTL3NRfsg+4k/BgqsSj57S/pldkqP3L18dzSJSn6iWYw6GgIGkZfNkBFH5s/tVbTsms0lWaAYKniqFUoxK3gjO1saFfoY7Z4P3lN4KmDSuIuGTDOPmtY1TMY7PxTufqzqvTVti7DWaWQWES+ZMNyKEG+AgwUaktbInKQ3MprQfc0HvcYNB5/28g2x3+nTH3FMJlvPNvz9XmVy6c/tWSrUO8uuETLfXLFySa234gVOTiAL0g3KHl7Zxg/YXAHZkBxpcitdlRPTXIBxj/dVW7pWlgLAGigV89RFbfU3O+g8ofSYmoXYKuophscybvX4SyvjnxP22H6LnIcwyJegt7ki1oHk2c2BOlt/gAaCjjEkbrgt7SRRWq0VDx6Ove7nhHJ5cOfduv5Sl8sYU0bG0+/rAiBbMlfrAnF3Wdmpeoszm7vZlliUUrJQG7/zun+L9E4vA6Xy8TG3W+cQDCj8FjRGOPeCr0YIMCyuIl7mtsZY8AYerA4ObP5viFw/+O5yRdEYDZ7JbV4PqOIri9TFtIs8xovCBES0aXZcMujRGSicLF3Hb+jcA23b2/pWXsUHiQtg2d0RpeY/t/x66LJOg+1OySoTUCIt5EaMHKccbkLUZXsFpNQDuqnFYbmUVoQ7Vl6vaDb6lqUpqV6QB7j0mkmcdVAFAYCtUy2B3qU7wA==
    username: AgCb1kXP7ujruffZD+JmD/FS5Viici1Hu3HU1g+wuPpui0oY5k9Z14/gCxqAQo5wE812FuFLFZJRTPBjjCYPc7DQvk8sLrmZPCCbRqJcMqx3Yvkwt2e9f+Ma/hbsU1pKrub9GN6TjEEJBbeRGrvm5QnKgI4Wheg/bEqFBObOtAkY748HMAvdb6qK8jTQiNOpGE+StMb5eFlpN8rARxeb7rzkvu5xDZNLExtMN2Mtv2XBXs0tYfBkjtx3aAA1GdLCBvd0/mlfuzbMnO2OnVCPFxF2Itq627gyz5fqlE8TGWSkXXhRDmxCwZIti8oXN+zXv4cd+QF+NY6SgMCqM5ZcRx4D6Og7+9KEUtFlwXoDExqgCs1yESfbum4Cw7truSz9dFSExPCOptUnTLXeykiDgdyMkgywYvZkztmW7idkM9VyqMkisTgXZZ59L+tqUO1P2jo3e4+n6DnC1+b2jwrt1oFCExcR5kbCc8RLgOXefZcUEZj6BprtQVd5LfHlKnZchE8qfp3mywjSm73MvlVMdXswp6m6R9SdL+Ob0I7aMb9i+nzc4dOOdovdivQ/GWVPufzyc5YQCNUQMS4OZuW5f1bcOQsWgb54Pwr81mk8aLyPm9Q1htsZ9BuDRHb9XAOlnzNbzzB1xonAGhNtWpfczsR64kE5EyIQ7xHPcaWr5gWzd2rSxFM0UPnSkw/1t/e8qbJDbuu9zjTW+Bwkm7DraxBoa4rLU7xU/BXuUBGTUA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-prod
    type: kubernetes.io/basic-auth
