---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgB1wGv/8ok09yQphqzbf4Sgz8QPCBhf1pYOjemwLY2k7XFAPW0fBRM6iOR5qVEu8HY1lJBQ91AHYkmSUp9Os+j5a7buJbn9yqxBgboH+VuJ3eYmaMSPCXkD6PNzJMET0VgJvaFm8sCNZlIus2ZQ5FsAwmCPo5c0xGeNVT8NW914hfiFD8FtHG4Pff2eVZC8mmOOptdTl99xOv+7+keUuSTPXVpbTtVLgkcW16lbs6cLr7XsYQlgNsnK+eSYpsjJZ8ThWjYt2by06VrXWy4GlyrhMeNYkeXSTrgvg/JGVwlGB1YJbW8RH51RygYv5wkf+OJch7/JZcJA0cojcC4MV0iygsfa7msL6OwBe2QxcBWOm7CZhXnzyoWHxIe+x47UwptRnWbCMejF0y1XwmZxpRetSQAIIcLmRPH9T98qM6pr/Vw6SOl5eBlmNzyV0wXtGmDAXh8eKtJ4saF9k6FREihaIuQE03B0DfcWrJTaVhe/fzMFI7EzGr/ice1/qevZuSEotoSdgaOc319gFbvxh95tZn7KwIgpnGzQUngv6um7D8MlxOpos3cl+9SAfbQZ/uBlqfbR7mscKcki8G3zsN7E56xbyasfIh7yuh3mwmMxVs8ZhkuYwPsSvGMLHV+XyIDn4gRnTKQjkijbZ7K566quKevH0HPXPr0+dMLNZgMBJTYXpfhj0TvnCFRzU6+Q1LQ2rnvkVjDws68NNHHevalBVc2wTfpuvN35bayHopYIdQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
