---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAfXVsmWsmtn1WEZLV8IIlUDcWUHCJNIuJGZ5d6bLN+vR8TmWZ3l3g/lVUUMqKPKET4VUpf85ZHiQ4Cj3lLAhKjIJzI7NFlVJn3/FwjHhz9t+/dZhGJnj67FMipUdIh8DC23YXNxVDK0zqXGWiMznsPwZy1C6UTyhfZ4BlmxSUbVnjgFh7Qg3muHykiJrcJeHptSckWwZY+/x+at51gGrePvAmP/6qBcuD3/VS/0ltzIicj740MufJbJM31ZkRvYVpJPnOuuK4bOmo62sWyl5tBRVME3CKnTKu8hplrsyX1OKAnw3g2iAoF7AsJQUhD1Yt9bgyBslSHgl0VDVzW5xQBK5rO7hu5NvsS6V+w3PMF3Zy/0OZQEBQ5kk+ktyi7Z6hP3pF68wOSqNkqx1C+/uBiY5MPca71hyeT24h5Lw98ObSgzGaa6OoaFdADENhb2HA1To/gMsoCMziwCxQVh0RWIyE4NSfm2KV6/ILigEdE2O6aJ6fK3Un4CjpZse5GF35vOMm+FItoeojhrNBs49a3kKwMOikjcay3WdvKL9s910dS9e68j15aN6MFY6aRfhGmYUO0OrNziSJUC8vC02WtdICXWgisZrUXP+CApaoHBQeywWgrcoiL5h6TqMwcBlhVGw3jM7PSUVJFwZ+KgZ19w5lxiYOA1tLJ51M9Ybllpd72KXMh+98hUGauBBOhqnNzr9ELfUvRRBy2McynvjVQ0kNp+NO84b71f1j4Du0dzg==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-prod
    type: Opaque
