---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgApBB+P4i+I7sZwwvYaaap7RQBJRwjnaTlr8PY0XG+hp2aJbo8mCuvG15GsjPXbdbBQufBKYO9Gu38+tHbhlnMvNol6Fxw4cQbpjAjV6Piso4Tb4Kwb2Cq1Xw6EyOISASyX3PCkmusXwwwt4GKWM7OF8RxAqrRNKm9RkCy6feeYOEll6eJjtlv1slVKy4dji2K7avCO6ubOUdmuI4gN4kj6gl0De1NjIanO7cwh4kd2dCYys8Js2ALEW1SxCECiIZlenaOqTIBb81pYORfK3gbFOxP90cs3osDYH1aZPUzOnI1hl/QpWx2yE7LBPS4kfE0sKuzIodOMKpAcwjQvP2PImOnotrS51QC+EMhh0HFUTZc3KaYEa/UsoAa1weLQK/+x2ZqrOCInn3AdeTsRBZoaG+rzaBby645xpgpJDRfkPkd5h2eQZrzlhUUGRAPMhaDUhIW/8riazW9/1fKpqALGNxZJDNk3sp8XaYHah6MO2hDdZWSd79AcReFx2GyuM/BSFH7MI7r1uE7O9fmC4HTTJCTCKDgZybE6QSK5VS+by0VHu2ksA303o/t/totONFgPXZMtEpl7G3r2CyUla6FUto63uw1iIB6ZtwOLy06esV5hmtTDZD9CXidcXymRhmC/AHbDaNCJUrKZl0qwvApwRLCzKEmUQhtL5PAOrdF0XGj59EieOd/ixPXKX7uRWSZJfdiO3oNLTZxZff21s466HzfGdSYqEtZ/Hk7NJdsjHIKAfKt5EyFoLOHx2pTGxBOKE+x7Kf9An5WYGgb1Qm5fzDOOXX9WftRz8onFzyRYcQXy+vPdEOKTJif2SNtzW50m5+1wc2262TakUbP7gDeYKTHpkNn3Y8tNvQGFgbjme2TLdVxIR20112jzL8evqD/4U1w2WN1/6AW+jYs3G30gDHQl8ns7sh6VBQUb7Yi/a5bLZaM7XM4Gnw==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
