---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBEnvJaLaOLEaFm7uB6hVniT97DAMurk3kPnoh38f8uPdKm+Bon+4Qi2TI6xDgwxXKbfwsTKhmPXboGaR0e1zDNS58dpXD3lfw8CHnMjVIa55pAK9mRm+vDyIUo2HxHiM5eXOzPHRYJlDVDQZS7xRWFpjIcP4oZ6KWLbDeCA0gNQC9YcUsp8rmddN/U7FhQ6E6KX8txDaxEJtG85mi+Zknw+LChOdFCnf+9WLKAO0W/Qo/4Q6cQHeZTWLEr9LacFbbFjenXXl72i9z9z42KRwC1dl5g07zf0JVG3MF8uBTPkDIqAlnQ1xbF+hrPGft4HNdohAiBRaOsQC4nGcBs2Pdv33ETplp+EoPxbgK8wGrBl8R0gbyA0z/r00ItzYJudwgiusM1s8K+8GvCO8C3Xy+T1X3apChAfYoWj7byy4Sri7L0hBt6KTVDs+3ViUwOXvrTWL6CaZ2bBQh2hDIlJ3B4nQQz9fhNKkyhxiBgFcpivcjAmCfpgVsg4cJViTXkJnO6RPYY+QwS6tbDpRGXtKkp+ZE1xIiys9ab0z03HY3aRDZG05RmaTeAzorw16DFfcg2Ef307qUVR/cN2X04VKMAaTO2WJA8k218soOzZo/BqYwhzzTmar+dKqHLEBSodasyuwg2vP8+2p3DOCD/mxvaRijqqEnAh6EFMdq1PASgsCo2knKysarNtfdLeeRD52sZ/SswrSCfYgzOV+HCT5uFdrCg9nPxOlBt8WlbVK/51g==
    username: AgATgeoluvvwxKgG4f4JiVCgCIyxe80Rrsn5GymYUZECPPiu/18QA9UJfRjEnL1XOreDZhhERdAwUPwm5Ppytx3bC20zzqbeKAVKblyPdm60awYFA+aI3CHOnmAfvJd5vKXgjzeI2BOfgYfx782m9QXRW2B90oTiNqQg6JKF4OHgp8cTmWIshDPQGaQMmaYDV9SoSASJt/JLWHgo9b5Xg16sFOn6s3od8OBXjNeMQ/S/tYPaD3MOMBQJO+0NCc/TbXfDuIPi2i/aWot96OH81gq74pZHqjndZ9cdzevf8SHRg7ihV5VhGsoJxSgQQoaqUG1hEF3uJiQcHylHGM7Sc8OB447PnrFLli/GXDw2RUdG7rNgjJPTOqsyysDN1Z87Q/i5O5X1sJ+14lhM/VJfFkJuDHIn4WdZealhP+hV2W2R+m/Ql0I1rjF59vIUS5xaLMce8pdAvW0EkMS9igx85NDAOJEbO8bxB2OC6+UkRxTaBPTPiLNGigHhDyyMIBgGjtPZoQ5V5QPu6Sh7oAae+WaoVEsJzYM8QXYJ6ftAIoJSJu9WDuH+lPddEywlUdw2RmBPmFVWU8Obfc8k5avV8WuXKcj95ieoqzlzr/76H/MuMVNH9jDw7W0n8M3GC959xIx8SVFoIJUTU26N8YLOhh/9DM+hwoYKNvzZfStlReE1SW/D3LIBzAdxYEuiM9dXAhnvkJ/DI5xkAwZexWuTceOpwc8S
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
