---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgBJ2J0KP9PhLr0C755bnRZvyjFqhuOSoQpCAoOPVoadXuG1xSVv3nr29zYtqMnIbeeH1v0Y8TUGpAfiz3E8Yp2FMojeQF9IJTzI4KFC8CUJgqahj0yMuHtx4G1+DIMOao6C5kS/2d50RBA+yEUIliayjgG8UKquzSrOfjcaIjIAsPMsVxvk1SXryVlZBCW16sFklBpgUyvLsd6zU3r/ARa8zfRgeRUn0E7Z37YfAt3ZG5a7KDjEBsXVCoFiv1o0UKgj5rhpGEXL6L36bchWkwMwop/vz7lJ4w50IKvPdClCOJSOljUr7OysKGkWlR0NONc908GQYZwvvsbHtdZxLQeE1rlhExwyS3lZ16NUyCyLC4ZrJNhmYugHb2z1ul7N6KKtVKFx/6haEnCPTYoH8BmL6OJzEuunoHKI6Bx28alHGZPBpFdfSq2Ehj2/57ZOjx/60J955oAmXKQ5XbOEPT5X/8zce8l+QQJnpIirE5XGQC3JEpoxSCTTqdEz81iuepgeNOR/Nc59uNmachfHKWvDkng9rIgWhFAAY5zi5VgB8t+SgnWzUEQkONBRaqIimuiU7odvV07eBRqrqqXJ49xR25T1tE53BRdCAgpdZowgZFWIcvqbp5ZPSonEIMtGItx3IngAXB/HXyS5KOEwDm7Uy0NqTq2MiEJdWp8unjr+8/6zuL9RvdFeD4/iIOJJ73lI3msSHgqqbt2E2rXlZj7choqMS75du++FlWMShQciIw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
