---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBb5T42YIKmup6mu9cXcKP+t1Uil1Pb1bXyzDQ6VixnwMSZrtLT3DZhTIxPzO0abtzu7ezUUnzxGKlY9LE+FjdudiHvjQR/z5GfoZzuoUZiZIdO7nCgnbOoSDs/CD+wMWxzBjxiwiouLHGcFvCXZTKmLDhDugo5XysQK8bAIK183kfyKCMrmMl4JAbeLjikb25Di+tCbg8mrIQIrqUmckLwUh/odPQQ4wXrVzWcuwSaclYkTybxqBTB5urm+oYqqzOrPeLXeE14TKzs0m5go+jWf3UVZgeKJU22BeOLXZQNy+1lJJrWJgoWCpjbQmx8zQU55BBCK1NiPZ5Xq4a3mD/CwHcALJRqduWWzzCbQ5F+ns3kwmMTk6N82nBeesngzluYYH5FuLV3Kf4vsNn9ZEk1Jyh+GmoXBFj5UUhBfYxWsJ0uPYELV4Ql0Q9LWsBHS630BXB0EQFNCi/w2civK5sQb/6wavvGwBhu4ZxPRu/nbLTGS+deBJ7ZthjqMbTeKIKgGxQkfj8j1gS8FSQt6NSMzhTNsvTqb2azLQ2pUrfAdYjN61Jak9VVzg7d652RNiWJXdR0fta2FrWC0uIOeYX6Zl030TkxeF6lj8NG0kVapXmxge/U0p0RLu1tvfTteX3V9Nd+NPfadqpTeJWXwVG32SQ9R0lZa+/9/C9G6yaGWeVvrzMkkZmsWm2KSNA0OiqZ919jBO/IuLu5BnWGUidbsCA8awDdtcqLmM8TtYB5+A==
    username: AgB8WCn6lV+CGzRyxDjPVsoVtnZ4AKcRd9yrZRxISKxJODjNjltXRsnoRvO++Z2reqE7aJoDe0FWMr2JNb619TSJuTZOB3PUE/ZEWWDNRb8wGGq/OX3y7rFONPCoCCugxSYllWvHK5qOWveFXLXkfGjfSEQP7ifGu9Fvwavvo7MnekDU5CwHTOBwKzT4T+GJM+qkfKb4Z7L5b7dSGsK05AKZAJqogGA9KUrejMbHvbXlVMm0seSzngN8vRD4ejGCw6/amYk94p9/vs76SrKt3vV9L0mcBZ7oRiMcC+CIEONPCRe/z/31gnSvL7NDmseZicYNPIeRNXhrROj9sAogTu2oq7579si3qJjv/HfRzB7I/QlBzpHk3i6Ks62UzPeAIisOiQsq1KMj8uiKLSp5trkbMQceHhhovh/XjoY9rd9WXgFTYHkzJY7jOhVe7o3ddy8NPBLZB6VHoOGlqFOwVH8ASucHYj4868r5Xx/vkpEqJBUF/Eq0x97mvddfLLfisZXwjBRvcTYDQ7+HSFLunvOq10SQjyUUabJdxSx/FPywtgxTg3pMUfljB86/QyhODeVAM6pzaAOJIEX+yURIqQYlA4Fcjkr+1hm16qukBn8P54lt1HXKK21MTSzpVpGbOW1jdCkD8SEL49+ikhh0NIM/0STApaZAizWAzo4nwcubbhLinTV/8iS+r3Re8I8hr/akYC4ci/y2+qdJADZzJf4OKOI1j+0z36BpWOT0qg==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
