---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAbabvZTIJ7aaqoTZddj3+ld+fgup+JidZykpbGSyx8t+l6dkXPodRf3uhxL4YqpDk+MPbawk/LV21og+3Jz3zQ9m/HvvlCdnBSxVfbja1TXVMOUXbWSrrL4U0bm6aD2jl8a6gPdVzAP4XORw1N+yEbHmHu4Y2rEKt/GqvSX8ellYU2/j2PyTaKNAJGnoAiNaeNeBCy19hND9BxKjEayE+/gJl3AvZ8d/eulY0xnpcfJrn2JnnPTaeY757MJCQ0LYhx0F0QOcBrqEy9PF/8zdfwJE1Ad5oVSzNZZ8ydnu687dGL80apJafn/EbOa5rLLyr31OR0GxZygazX8sSNkENHyHY6c3LyEHSpHIeG5zTuQDc1hjtKuLwHx1ijQQaKxtSmHp8a5y0CSSj7enIYSnhJjWE+rGTh7P14aTnfcMgWIdF9RBThW+KrluRZ5j+slPbHykynzfloKOJXOXMc557YHZh7gcD2auM9mwuj2oib27rKeR4VyWMkZdr+bakdBSJMdsWzKPLKffmWj+LgUZ4jGDI/1YQ7G34huIl0MWWZHyHlqa+FxpN6hFdZfo6Tz7b94Q0wiMi8Nr+mEMpB+Ow9Q/sqPCqGo3v2A56xf0pOteAMR4lAO9eujswY+3OAxFtjbSJg5mQPqumE47P68oG2aHCg/wvOAfFn1W2kQ8gVGUlNkP4akdj5EQvh97cKywwOTVg4clHCRBDqqZj8MdqZ8W1u7mTkkKCLDQe2sEHvuw==
    username: AgAq6nIc15MjudUXoplQo5fsL5HeKZHXw1J9vyNi1VBwN9OqZaEyV92KjPu/Ih9WA6kGeV/5Ih/NP1ojcdLY9iKTXmKhHz7qsWdSZsHSYfMpgHdHFYv8PVn6bbuzEGY6dYfdOsRONm+C0O+Y31jqu/LMXcytHYGrECYFBgLPNKqsHgr2ukkfm2xUGGVM4kKMpJ9dl+/9kv0Z9wjtQ7hHalC2AkNzPH+rgor//lFgtAifDB6/ecXidt0YS1Z9NmaYhmkx2+ZyQx+lWT879kviFpjAPhZhLlfKDXtmWVEDhaLGD9SUfFTimQZYwAfGl0i4vgweTPPqyQnRh+/msgPmrKuaLRR8Xnp0jP87JXp8rJ9Ct1jW9bNPYyq6m1sFa71Vjkkx913+nYGETpUk04Na+BD9Fjf0RDnnQOKzjqOq2wvJfqgH15A6yNVaBjMqxQSgCQ7sxZPezaEAX02epztnJ8GJI49Aonc7t+bMUoteZ+55A7qZeLsojQ94kjmUkYbEkg+aJ/6S1pcR0CWdQnAyN5IOxNWVoyBT11vjU25LBid7sxsD65MYvFuZ5glQ09BXqsiq9TP86XN0LZDmM7l6YlNVDoG6b2FurB9VPkP6TCt+aO6CvNz2hOJhE+EOUo2558QRYt5ZOssK2LUO7jIYfflvrnSf8Lgr/Pd57Qn6e6a6ay7iYcrID1C17IRFWq3EPusJcZvP5AokF0ceAo3tFsdHlTOUDSlpkqUoe/xJqg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
