---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgB6rd2l0xOYM/En8/7zbDRkc6aW/Tc6cD+xW99fAPAMZPZfunPtSY05x5yrd03UBw1lh6vIlx+uUayL79oZ8U0NqlRpkZJYI7+A4J7Fcv6WL0ekYlHzr4Sq2ZdODGbZOrVnvJd9JdOs/7HVB5wg+ja9hL14BF5TK+KQRBpxoSucc1ric0Qo14zkMnJcRwvV2DXqIBYZ9vzRy5teKdTDY5MChl0AwCCda9Zlf8GImCyohXaM/PiOEOsIKoaWCd7DK9UWfijmlgUyFnDdNt+PfpP4a+gqGYshIktr/LxPtUG2m3TxBQsfFSw6H98EPrDagb7Y2an5Pf74Ftsg/imEzBcWj3OK0otjnis7iASdbFgveJqlgoJknNTwW7R7dFzY840zEmhdz2Wn9bRzUInOj16Dg9r2sDFiaj6zK3iTsZLtq3FnO2iqbcKYGWRQJdQroUxsB+eX3d9ajCpIrwga9iqyuRDIatbd4xhlPBW7WpnS67s5gRStrBIo5UnFLOCjl2l522Rss2cQg0Z4f+AGxIU6oZN4ZOntvHe6eKQGP+ExlrvbWUGPqXIUbCCiHna046KABDDmI4jzwDs05e9DKCCdnS9I4I1H5QIWhaAcKBcQiJUSlydkjGlaBGOu9qGU3QsCan2OuN91ramzDXJuL04dk8gHcIVa3/KhQtK1QBoIGbYyoyQo+1NLyvWODnyHHcYERFkRBJHyZ54XtRnxKCw3qioWvpm8aD2pRP8WPMfOaQ==
    username: AgA0rdsf3ayTA0DCWcNZ+lNPoipnCoFiOJdbaLglk+hDik2bEVudERkRGvpKNiMh79H2u/v2JqTyKYsZNRc8KPQS7crbbgV0ynaBTKHQbezyIOp3fOtjFrUTF73MZkIQWl2x1vs5LMiseIexJkrF2lmhxg3a3/0fsrxxGBKiNqjcj61jXJN5tlr0GYfLeP94TuEHZ4xim6gZiu/RevDZX8YXqiaF7Kjoa/LB010hVWwaqKNfrUZwtI3NuUXxKcPSPrlc7ooGTeJsnug/eATr65zF0VNkLTduI5W4NUJ9igOzjQQiSrNRzIdvK4ppUzFU8KKrILJS4VXl9v6VYleSmxfOt8XGXJUWRfWI5ckejEzy6gfIl0sI/Jkln6M95HWplWEiYD7QamEPJReRdi84UUYg4q7o/cG2wL8MA/Q+85z7xam226FZoBK3fZ4vGr0aZg7issB/JYVkS3R52WscIzm5GvhAv4VQUh24rd0oGYf14cQVPuHHf+GtOwjy2c4v1uf1cHpN88JUU2A+1QzX0fy1Y/3nEQuvFuIvi8DDRw52lECQ7m3PlAnMb4WZv+fqGI1CGc1c3I+cXE0FQJqyNfLizwoQBJ45q0OCMctU5MmNbMU3aBSgOT54tS2hEcihrJBcKfApRNMQKrkHvXI4oNA4RM7SCsdORJcj+YpPOYpF0Gf4xzHFWN3CyzJhRdRYRVv5i590YrS3dKLkWE1eL0d81Au+IcZKaIakmVcFcg==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
