---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgA5fM4zLQsLt95UqiQ1JHZacV4Zw3jptBGKIrEpD4+qSY9RgENY/ov8cxfGlKnLwbAU2vCjNzxxQsUgh8ZVS7VZ+mGzPsq9OVxZ2XxPnQ7pQjHswD4W76hdePdCwskb702RoG/MHJhspGZalMPk2sC3FXeEdHH0B2iFgp2yuCNa71wYNzTuZpDGGkwHth5J2d4bA7K+LFSH+8wa6AyKEP51AIayJicQnzl6Nr4fU/fF/KSHHX2ZusDUInJH7Glsmjmnur0+QLvz5NFIvCMTGfGRlSnRrIALsr+MfWN1QcZ6/D8jvWLF3JE4Mhufr9Nw38vCiRwxtfxESvzMF44nrMnAdvsG/eCxRTImOZndLUif2Nsa8PrztFgFNPRSsvfe1GOqm6ZNnMNHSMR3eVSgaPR4w6FP/gTAVAx8lVXAM+3yiIq6tpGwkH5NXmbXgOhBwin24CC7IZbX4UWS317LLG/BLKodbibjbvrqHSnxLzcU64/D1ZXpN4d8dYRJwJxHZ05dr2hagV3cj1+OHEN01J7l4UoP9Rq/S/B2WtXUmVT9oBCiwLzIKxtsOKs6rgRM9qEFMq6a5kwExprX0h4vGbS6H2/VCD4BX0wt0jNwQfTZIOZp1qjtOV9Y1Ia2B+ZsMwlP82oAR9KvpTu3mk/UNUfChXtQyikmc12XLz2A5U6SHE6xMNTIMhNrH2Jx0fynEXSQEzTjfqb+ei7a3m9FyRcPFlOpisMVQbzD/etgLEO5+0A7OyT7xhXkaGzO8fjh9ywVL5iaVXFQkADmvPdyiCAGl8kVyAuyZeunIlkNohwhSuju688QmdWHiBdHKMMiVofo2pUWIyllYxMLAH1fxjSHq68Lkily4Fxnw30H2aBcMc17o//tYXtKTSvj72+qG8Gvo+ZXKgPtcID5VJdVVERqrxP6fo5I5laAV5jFwlZjcScox5CgNSgugQ==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
