---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgARyjFIjPvXuC4tsSbmiSfWvuiLY9qiXHs2OLaWdSYbnqVbwZLZt+kfY5s0EVIvvaxBy7RIJo8rGTzlXwWTXpLejyw8Lc1yM2jHX8KLh7aPKc1svelQrqekUYuOtLBG4Dom/ZgdS8MkokRKuZ31jU5BOzqa1K1iVjqyncL1ECLIIrqqVz4+HWQvHNHLTVUKda2ySrMG9TIFMk3i84Lkn7Ct+bzjEn62yLpambN4pz2sR6QpuDdFQ1FtqZ6M8/iF0xxy+r/C5qykkUj5pUS1hlVba9WlFvY9Rh0X3rzPJDVu5pOxKLxEnP95rDDgZx+Utpz1QeDDVnMpvhIv0EP1DputKdFty3H3ZZBDXdYKS/YV19egFVs+zcTnI8PLdsHAyLRlYHyaJhomsD4Yk5Mk+RjS6977H1BFX4DmGhRuaU5xeh2HD75MBiMOTJFx3bDoUq97Cdk8GR0eDh6K0ZDJ3Csq1aCXr8CfLJS7qSv/x6CK1O0PQYU6DlsiA+EcGG+JW28zUxRted4bOZFauVsr1v+lq3UThGdVJyF9vLx7XbCQxxklHTsAM8Qblljllvb0nz2wcGdF3ZN9ylM8Q21Nd08WgDKMhA8AOGnkAQZiLAT/eX8lD9euHVVTGMXFgSGIzvnNp4WhsFmqHF0l9TblhHYuhlbOL9Tqow9e+Zup6HmCiRDmsJHn4hOIvbnDpeKOizvDkmPMhbh23nWk1LiDxD6r812JlZcwKBQhD02JNu3mAw==
    username: AgANfqzZ0GKGi6mPQgiyElQLUrcOFaoBLA5HxpPFWXW+5zeN9AjznRD8DKtsmQBKFvHlGXUyrI+wPw2nuvXwBmEC/Jg7MekBWzimLf/FInS11XFDMc4vcW51nbPbwz7klehGh48mI5FxaGBq54aTOk+2YZ+OXf5JBr/CyTRWvJyQwI49tB+KnpiaTFmPPZSUIKdRts+lUwgHdzwl13nQvzUFKVOxIc21Yu1MWTLMgiP6Zh73dyFSKd8uLsiFRT7mwGhhw97kGW5+k3WGBNNkLp+ANVNVbU12eQUmnhFgt8sv3Bu2gU5imP00mVDXzpzxFMuDDGmgqWor+vebDErbDRi3LE0ezRNG6KT8ugl4uDkuZQiaPZ3U+5YgBtDvkFP2Dl43TwSxWl+N0THihjVfkbUIdrJNn1s3/EWLw1dTOa+HeRcbSKZzOH/u7mXS6XA2zPnZ3A6lUCvBINgrG3aiHAEyM2PuSvHhm1hPkc62zHDRGJQgTaSXmkUH9MhHABzmypNflrM/qJWdk2HRxr2LI3qVIzjAfqaelyVVUrZqdArLVgIsx+0G4Lw7mZAgvXX1ePRaf5OY8TtV2cOGN2bUZI+g0ESbkjejlJihJL0Gbe1Umiof/N45/AMK+Mgd8CWF82nObLjrmiuKeJ9Un/7ODZBfXCR1ecIVHXp2gY5p6XZm7tOIMUYiqaQzRIoXOvZC5S+dyi6EU9UaRb9DEpSgNqu9VaPl8VVwKOA=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
