---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgCFzv5/sTzwdXitjld8aJ6yATaWIOavbZP6Qh33v7it2TN89rUu7GNZIV1gDCx1t53mgpkdbLmpvdvZd6zFNGJIsMriS3oDuaJ+uA59Z24gu0pKzFGom7192N0ejB0wnN4CPAPcb7PUeJs7yXTzfuCpPWVrujuMvGKBr/3moaTeAY9zlfQeAodnxVQ5kKVDtnV1yjKUyEvQUjoIelQ4x8wjl23mcOqgn7cs6zG/+f/RktRcSxg0Fbu4JkCANRHb8Y489XVyCYQgPXO6vYfo3dLuAGH7x0o3GOwWm160dtNN/6A/4j/Zvp1xh21xIhIlupi8n5x1Jp17+pwq8167Ks6FMiAOAslupk8mlwS9ygFBAp2rjhfZOOt8jjnCHrS+TlNFJqyzwOFiea8blwsjp5gmHHRl+zPAdEY4PtroYdI6EEvhCzPShpnpxtYBRwqN9sfryRQ8EaCYZZmGR2+H1qWzilxHu4lh7CDh1iNKGUNdkFucNfszU0BbBN8J2xKVr45zJF2X/zyuloONj5QPjIAzkd/VF0kVc+gznOzi4T/74b7nXb5EisCC00SbbrJL3W6zoZ5em+8ZMWOFjTUXgRshncFwM5re9efN3m3sXe52zpH9wQJe24x9il2UdpdVUNKn0MfJAVG5ROokY3QSRPKXte6TkFc/79oPQL8IXC6dQbST737aWU7/+RXKt3OQ6eIxlI5+udYxW0GRDzfoVX3tqQ2J3u81ycI1AA4xF15/FQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
