---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBEftLYJXxNbYV1+m+JLPenUFeWmoIKoS1Xzrg479jFhaKMW008DUQUZFuX8fqpfpC2HOhf+2XZq8tGXoOO+r3zlMDzwWxPmK9uJkq0pL+iI0FBKloPoMZEmwedoy9H2J2H4X6gMZmuwTwSzvZ7GJ/4RgceJcSwEWE7RlxMErWHafXL4vyVGPC1nHG1kiDXSZSXxO/MKWxafSM+i7zJ6EG+t9vV+Q7msK96aFmBM2bMGjccEDz1l/nfCRuPm9NrEtfdYmMY9+EOVRStI0ZC4MaQ5Q7PnNcIPBdRbLd9XxxeIaVGl6317u3WxmxV5Vc1DKFhe27qXbKOMPXM+NsF2So0CHKK0TZCXK8kovXyB7uvqbwN7XG0uoxWHvvE99garc6WshPCmvkQoWkt9/Hx6+nYiH8Y27Qx/Yi7qQc0jt7Ykzm3776u29k6HJPLJnb8X6mcIST0BFg+jAFiJE0elQ2znQf2PwBI99a09RF9HAXN3XLUQvxDgj+9CQ/i9+YEEDR4lmwztP5HcosK6Mw6snHE1dys0mxbiXAk1pe4+h6Usrw4u3E41xstieo99XwL9svGAqzPanmtlBmaJIaldF1hjU63SoT+7iJjDilxzf4SpWvD1qLV/OTy9jjxWyOdTFL1j8AJ4eaQ2fhb0BxVt35UTYBhP+zibbBU6l/QDwJShVLSPoRpgikwsyLbRmrdjFHz9LVJhnSSu3HdKYT7hvUI+eUVAZMIDnMs6E5kdSE+oQ==
    username: AgA+FoBEslfgM9Al1wUSfx0yP/0DIekZsrg8HmJHiKwmkMC0G1BA+O14KGNobhcfvh/YphEIKFim6zmaAxLkBsdSrEgXM5tun42IXxjWcmvvXMdj0pVh09UMtZyJf6B/TlC9PHQhMbbIIKIhX2CUjxKrghneHnYqcM8tNvuz5gFxzhhWTGP3qUuoTai6TjNZac6a13HRY7sqZUQOjDRjDRsakC4DF8cz+nHsQUW8Gc380Dm1QueBg5dc24jgdOpPmlIbpc+M9e8QryTRYUgIRbBaUSjGDLeahfJb5JvH+L8nN2QUVYVlhEt25wZCpwllo2kTLpcPEFhS4MB+siRUOLAKFx3swyQ77SfR4Xj7D3fLq0Lqyi681U3eRLQb8RLjVx2dKAoxrs3hLtRiLpQabVipfdBJheAL5E7AAfWF03gxuorpS3EBnp9WjSC6udV4c2/IhW4qyUDL2TG5sWcGUX7ss6FWXnv7xSWrsTMuvIhPCmFEYkD0KAQ79hTnLHRWLlsU1H6BpQeedoOyXQpRjY5+SV2XVoVQnJDgs3REX936pNbviR5dnIgnKKTadXN+RBmCcvvv62x4PGDK6rfLUpYi4gv08deqhOGqyHvDkDqyLwcFbrdu9A6pYJTb7lACsWM/3EjtnrdGMak2eDNzR1rqYLD7brhvWMaKPrjZN40VneJvjhuqN9+3mJGsD9g05qBsV5X30/GytT7kcmLvCz+GRRVTaBMmQhHurCpebQ==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
