---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgC13dI1A/0CzKnFpphq5UQXgyxobH3VTQlBY7o9MzpnSKjynsDToaKlhe0X+s253eXB+/dStNgYvzFiddhohbb5JaUQlcen5yWoGwWfymRi1xpHCw8i7znzX4YNbsfCxt1a4k4BRIOIvoBU78bUmvlYL1djH3P2CqQdskalBOcdzRT0LXwQNo1f+biKc/m+p6iwx4eldQNuu0+7iO+Lpo9vlsKvgXhMKf0KKkRIRWozAxOPlx4fNlplMNOLBCwH7rbkWQgYU27XYNJOK6cFgOAjPTUlV157Z9vqcnN3grVHVT8QG7KVKIoCLaI3GKLkg+HBfk8QYME3TbOimaN7O1OTBfuQKxbvCTrDB6lMJ0tZVENktG0bEB5ov8F+ZnxiMObz/t69bHQDPCnnjS3XcBl409ET9+zAxjYNRo61OSPeRhrzvxL5NtkMThzczy303dgqV3Y0WanVfkXSGCByoz2orWec/oqQ1i5UGNU9eOgBDdrfq+N6g6rygwXWpfcetES0roBkWHHHON3bAoneBR+sfvDGTwl5My0HgXMze2A/hikYPGU6/+41rssvKYU7vL5jHpUZi+bnisyldaCwAv3lQ4CzLTgzqJ5th0aU3UzRkpo1eSoovdrtUrQfsGUzNICM7z+cI/3PtKlkeDxtjTt7IodYtWG+J380HmUa//gZ22YzUDwz2XWjwBWXSz1Sgvdw0hxZe5ZmqMHFoCNY3Y6e8EF/evBNwRLlmPGkT9GQBQ==
    username: AgCEcrVqiUb9EB1+lJnPRbZj7hy+ix7c8limoNFeoqQFBBl9GDu9yH18AgE8HFDitKHKBPVtm8I4lKOmy4e8cUovVxIgRuNKG2XKUAIhmRYaCM2GAr404NDbMqQLHNSbE/1R6qcYdg9A2EfPS1rbnCZqP9u8+tccgESpBUS6rtd3bySfkL0j7xrcGjpPpk+ZSwO3qcTcVC3XRiN2bepBsUe6IQEsVyP6uFZN/lPp+UAUGeScsYnD7Ji26W9ADAoHUsJg7dKAOctrRGcB6wtkzSg/BYiE7EndJhueXPjF/N9K/XVFL1NifPDWQiG7qt4ORXbDOM+vkF0q24lJmExn3gK3IGmc1RGplkst3XW3/pJ2ZKD9+8kd/KhZTagjOOJ5CwOoxAxxVaF9xsIffNmMvAqZOEBrJolOlZzv4RJF9nq58yzUvqws4xgt/VNfW6uTQjIjNCRQTEFpK5sBH8i852cbeBnO1Oal93SYrKbEDlOE0Atrb+KFimy1xIz/U+DeRdjdsvVSi17uxxVU/mH8DvryTxVF0LERbwnK3Mvv2n+wpjDdwB762BAPzyhLL/Pjj5JhDW+Ed2q6OPcE59cBWvQtKcrjVwgyALklEm1o34az/EQqd4oQ6tvruHnGxjZcxmYVTvF8Z3gUiUj9jQLkw2h/Y2kfYwphgWzm0tApzx7apIz+ccekxEU3W4gSjFbHgQrtJe+k3igKRc8lna6v1ree5L3H
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
