---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCQ2qn4PVD/uAEgkuCpQaf7BhpgpUOtKvvN9i40H5b4mekQka9ZeIiIXSIWb4fW2s08aW24NVXo1kUaO4TWpVfvHsFmuEZseBenPsZwnbq7LDe76UT6A646YDrPQo9M8wnIVhP5ZOptBASVYU3v7/yzX5GgyHScCuyqqhwr595Qig/mZTcl++713a8NG4C+60aVE/u9Jfr7Ic96hWH2RFVP/Sy/OoAftRkBNnfBQqv/1lCcQagGGW6SgGG1bE8KmYr+jFnaxdgzy5TcaT30Or/MAkUeVarRIWMPFfOuK6hT6ksIb0iWttG3sX+NW2XyDMO+iFUDfSEo0IDmwkQeyECfS9DQ0x09F7gYF37Gxx+1f9JJyPKRjvkssQa2hI/4DhbvKtADKRjbJFA3rORf/RtThiWGqDXjGpHCDEJGUrU+qrYq+XMFfaXSvooRewgpSPsHt+V3HHf7CbAPpGEDlVUg8NtFj8KpwKbPmOKn60h4pLmbtcRKgGKAvNWzdwsgioYndfqDrqvh0dQRGGTlwLymIS9ld665qIs6jzwgVmAtQOug8D0ABpslxGl+mCPPmbhZCJzMS3QU4rbJrvL+Tyvy2CG/cqhVxqZErSFNz3576l7XtH0TypALvwLBjJQqm1EFT0RFRF7Hh8ZXiXs9Bzj2aKa2n+q717v3AZ8au5k4jpcL+EiVMIwaXt4499mWCB3E3OuSms2uGErgN3vODyvEauqCfEXw0or9YA1V1VeUgA==
    username: AgBr/CGtuR80e6gzGS6e78udoKl+4iyHi84zsRe/QywaSTLGSM2yD8Vh4V59d7xAomghRj4Suz8x7b0pAUYCbaKBNj6TGCtBYdNUxITHTh6C3Cl48c6kBpxuRgwMd8Lm1nT3OlDHhra9RXJ02xQARa5GHKw7QFL2O0aQ5SB+GTPsU/tuIgFtZNDpgMwzta9p3RweuC98qcPGx4UHPxPQ73l6eE5J0aOLCiOPqE13zGjepfPUTzAkEKZxA8b8haMX5GtqLhhzeRAEcVTzUIH2NB6vWws/156q3nsWlFzSViE/wKzbjt4EJvVUritCq/bS4fubFCAO+FNCkONrFBihh1dQltBoyKSHGnAqNt68dlECCQbGeKb8wav0sNbH6iqCTsc6zHMS5mGjeO8USVHHvxWUeyiUKxZD2Q5a7btFIWgQXlLQ5nUNlyoZLYFDd5fs7fWfxDrQhE1fXjNDCxXTrvA6MwKaXsI0+KvL5z0JIJiDIoZPxM2xPsRuu5JWye/he7OYlj+6LIs4hSpz9VapQ1sGRczYZML2I4S30aNUJQaMG3sQZjkOmmDj0zGjVdqBZydOtLFiEOCju2OBQJSL1xk9Gt+279waHLH4dHaohFwznmNDoPr8u/vznv3SB0HMYxsc7Mc6kQjtz34I0rDdY0Gb/UxAAjt7eq5QPBtzP1sUgI/JU3kuFJxE1GiYIGeEWYqpPWwJac1Umq8fRfPjrhBQCdzt
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
