---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCJDpnCmaapDVrxMXDnPdSIeuDzK+ryGQs9zTIoBYxkR6hG1QUN4FXQ1M2LAPj0TuysqDdqMTc30OiXDtEMG0mNWK1PtwE05zsHUijoFw6nDxTry+UC8h73bLGGn7Re/FNtGF6aO6Df2pKbkT3cenDYXVqbhVLmkmgkVsGLrlLNPg7TZJbXoGrGwNkMsmj9RP+UU/tzF4KZvIDr4Lcv+3Am09Y4+Id0uiRgOiJiedJOj4H+Y/OEETSkXjYPV7TvarzfliaIr4Y5HcXDIVtxiRIMRIRXQj3OX9zlsUPOZe9vpKxXAiRyFohP6OX2vrmgppkdy/NhxvM+6we/2lMmnRqW6z2W0+qrpJxnh+L8k0UTjIKSWzOkG7qUy6cLg6urv8FXLl/TZh8PfuCGR7LMk2kki+HcW4yMZFDBt7Ee5QPMdLz18+nsie4C+7zHIkXKZj2mNsueG3MpdvmDAywlJdM6J6XCnY8h0gKi1M5s0TH93l3CQGW4nSKcw3CfzX6L5n2/nS5s1vMY9ACdb21TgqCmNIK2tJ1xN0R8gGAaUY7TwZuaqg7P6hvRDzqo+9MjnpWObtKMFSmpv1nJeNXuql1GFvrVv6SckT67TrUszvm6513UXKAW1rLsqqWf0reaOvfOLmXTilw8so1Q/+5rUJ8PEueksuC5wf6OdC5vXBaQS6XP2eQvQMsS8SzgEo21WpCv8Lc1rBzKWG+19CZ7XTqFlWdpMOF/kjwFWwR6g+rRMQ==
    username: AgAE409PIIfusQ4UkG5ioF4/WfZf+JDDkDoUs9psenJXg0H+RffLC69WyMs9vu/ul5HKT9Vah6+X6Y2XEhy16UVmC9ftU5ObaohcStXCT52bESb4fD3Sw083YZqBmf0bGQicMM3plHj16J344UPLIz0ZA0Ha4Z14CwrGxuO7tfiNLAjBIzoiaw198SiL1oc/SRBuPuk3MFy164bEdYEtGfs+osywZQQ32qKwdnHb7YVzefuijurFYjMLVLPI5eg2e+szmUTapb+RhRHtVxoWApxn8Azuxwvd3Mv5Q7i4Qhb0kuVlablM2K/pUDTLzQPYHnr2AvQqdizsQA3wLtzrigewBDQTDVfRal/+lbRung2Nfw0/KLkJU0XP336CKYjLPm5uSEdOye6ldYYtEOuF6+HgoczJNfO5+jNvaLtQyeXTC/u8fuQr8YtcUHqNyMK4/GTPinYPECbogDuEa+WJvfL3/XjWaFUOgv0n3bsyXs4/+qe1InmfbtRzB3N1fEbqb9iEXZtJUAjvcuYZJorz7M30d2aqgNiDD88WNaa3Vh4ZF57yT4sQz646wpEKrkkR7HlHPQ+YAlKygt+mXhpId4WrTz03u4DrTBHtlv/Bg3pEWFpkq7KewfhnxGW8orIQscDUnOCri8IUzPguYgEX/iTH3UpgZuXMizsbxuXeUc0EuvIbFrJ6V4jPSo6l0EdBw2LmvZ2kp22M2XMUVPkMhZHGyFQ93P6JUTXIdWbiQg==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
