---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgATjoVgJRXdaiBRjP4P4TOMa2GdpOKcJUPCA4z+KHdLojbBecKKpKY4vvAR2HWnPt53SegtT4w+L56xGlCBdTSOh3jCZxMKufRqXHy5ocNzrEb4GY/NylgOHasZSKPzDUHGyADsDSVCDGjnq7nCRNtyxsofmw05WPfOzm1Q6+18VfeMYNrLYyNo7WIt79XmS8pWnkPMKOK7jzDabWHCYDF0doxcyhIg2aPdxjsWAOfo4GFN0b7mLDlrBLo3MEuzV/LYFlquEF1bkkrosdsQL84erOqMmLN1EwPHdBJjJiPvSwXHDlSGc+K31zDvYV+ylnLosI3mbQd2H1XYi8t5zJwh42hNC/2UwXMsY7OruUc1D65qqmFR0IliHx6penKsZtCBsLyVMCV8CX3v2fHEE1OGRPx/b062JWnluZUJqlHZ0YLSWBg6fPdNqs35C7RkkI9ySHDn6ioEd5pdWRjmfvdmjgPgH7xVx9F8A4m87k7Olf2TU5VX4d1uGwRZpgOUZq5UUTLC2x+Yl+ifW+yk+Bl2d/62y0BKcf2KiioJoeZz1how/S90QwbxTBehfoXLaG2ajlr8cbBUn6LH2+1EUB/eurlB0J8ui8PnDlX4YWUdWa2P7gygE+kHY9dwLmZE+IZpwYp/F3sCKRwy64GFOEJYxI5F8wQvLqU2A6yw4IOWt0oDEgZ3fMlNOo5yXSsWelJbzG2aTnbWAPBim5TVcHRMF8ZyjCaI0B2LmRw84MrzTMTw4vvYUl7icC34BtIyabQCZXtxVfzM+LAuLV3CuHAX0oKblpg+44e+ZNgPyHDTX1W/XVYOmxgzbWVD3Uq/W1Jy6e0xzWlZ7/nNDhBUtC5/X0xKBXnj06NjlK8UJextkNR2r9kVlEjtnDwfIB4GoGM0A/xc0LxHoRQ3qsgFqoXMyIhJkVOKJwaMmJjyqBSbq1LWAHFfJKLOqw==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
