---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgC3j8BGIqC72yATQA96yO8XDwDLsljAr5HNl5NKPvVbBQbXveeeZcnsXBtzo6/vyeEooH967fOQk177kx9qTBTAzrqnly+h9k7TOTZpGeYZafZDH+sOkQyxDcLTjFXI6xQFLbtuu6YLL/PrBkDhAi+0W6494TR7nIzYNEKAAUtDvZTomjaJv4PdSfdmASh5hUOH0cWzxNKFm0Ga144pQh2vsuiVON4fzEewkufO2JPq08hPhcO5MhMk2yK+wZGPz3jp/ymTI1L/v57M0jEtdvJ2q7aS6NLHGTRyVl6U0kJKQ0I5cr/U1q1yqXr1qRZMO30jLiPzKy5i4g7lG5AOg2fHuZrKfXYhE/74+j2oAzKzBPKlAjJaZzsAJlTYdu+hIAzvpv9bZp1UiKFiDW8gJGwYlXUfvt6XsmWyagmwHYY05KSVt5pwenqkBP4ng+L83tMhlA+rI2AqeljtkLCBNyZ4BU8WrlTxEJSoC/kFLNAgSDiifpKH7M54ue4K2iDiEyKedIhIWYPHUNhemLnCZ1EeX7/G0qqrWgas/CP4sCf42xzTxokEzvfQVyXokpoIhmdkkqHmSc3q1uET/iZSPr8yhU6ELdG+jUulhKZ2gWOZA7xxsTiy1OTOd8/ScPHjbgWzvTpbb9R0e1cGT5o2lc8ZEUrNmI2XrB+W0nQDhYruNJIKmZxtrZnoffVRIeHUnGzQWtX/4s3w9viNF8YbIcEfLz6KVkno37blaTEqAHAQxzczLioFbnyfoc0GELypRqaqCQRvkQhWU4p1jnfSaXCNU7SLcGIQDq/kJR3ZzI4HsnsJ8CAUbo+U5ME+SxAn74hEYyNdEtZIdElHi15Ku/A6mBQPnPlT9KBXzGxPu4Wq6zOCq1s7cKuUMHlJFWMGCijxkRf6wqmkaE2RfFres8Zh2s+WcJ6AWHT5xiCgD7lm4IvvM48pZtUgWA==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
