---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-ins-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCUZyP2bfjr4cOC3kYZgEHUlMdmh0Tyaklba+7AqUGQ66O762T4GECxxJ01FSljkxNYqSLQ+E/RlSW2bgJyyh3r/mtLsp+/FfnfYRPup6NiLfvX4aQIh1p2jkQ1IF5OpjMu7y8gnpqM3u6S+vt237vjMWHfBa+nYqf3/Q+8Mp2gdTzLeFcljSn2Fh36gbTfza+WXDze30AoP4M5IVSxQXa2zVMfFX6o84ZLsmPvllx569+loq2YW4DVhSZF/CykYIXBZFj6r6CWXNMwtr+Omygw2rB1g/u3NmBhDAJKdqI3AMCNcWEFwFeO4SCEeoqkC6J+A2zbuKg0faUJQ86nH0FPiJYGZ9FNRl57gofpt9M6zTYICdYkbzsb9joUUWobLOX8y4ytQ0y8DYBip7GEvrftiiXYHzotmOD/gy6IFP4zqNnHpXXRiiNIq2TWcrEbokI0ymDFyVx6Jc56jPPXe+rXXRwnb1Ck48V0IhpjEeExqjyEgLpwqzKTDUhSBPPTBrFesWhO1i2Dbqy5nicGnH9WN5AhGgHxu3EmlHY2/6R97AI2ODZU5NtkW2VWgbshEp9Jk1VQLfRKfIC1plhVMNzJhdXab0GnLecAehoE3bHFcRfiAjRCacF1DM30CTAu8JwO2ne+9iNoiJ7HAnejS5y7lsLqrDeR24OtbVuEqf/vQ34Od7BvWoNAJN72BxnrDsJIBsISVYg3Qg8lbqb7R1KE/zCYlzSqDBZbBEI9ycjJZQ==
    username: AgAyaTVGPu4mEBMG83Z3KUPBI4GNV74fMsF81DnxRBTI0mNUJiQMrQ8z5VZuMLJYtL8zp9KHQ/ZPoN3BFPBTrpRtnLfonC+MkBOneiqbp+kLyjlWRg8/0l+YxTbH5ig2JM5ggoUmPnQsfOl05Ll2bxvGmxEID+ydFo7ymp8ibw4qZ1O94zq9Iuld+/WGTVtXj/Uo3/zekDtAFz4/M6u+rQq9gaQkfBenUs4MgEbLGnZuep2WfmY9Mqcup1MvtE7IHV7kRg/fpJ5ii42lnF4bWacM1M/cdK5EzHnIaygRz1uITajNcYFxqNlcqBUOeqMO8JmwzzrIdaGos/s7Vy+GA0NPduGX6khHDB7rKG7sU1KbnspYn2F/1CqE8TBMSrlGq54ocKL7HGiTQ+HyDY8Q+pxRJtz2OjsoScV99/y3j8wIZquUlBqrfo05XLzoCJPYlACCBeVSwpTvndUTOuxpqP8cC2n3uOspVrb7AL+gAQUxSeCPOZrcqH1u4S6ervWF4T832D9uP0P/mUqSuneQaLqCyZ2MctRr7X0dQsenFcvFSpXcPbFibYlublGREg1PUQnPp4H7LcN8IjKiMWDy3aVR2iSpS0/sw1dC9DDMWX/W/TYp3F7CKzYvcxFUxaMo9rxOrxFaC78p93R5WKlsVi4hzlLA6yKJYQyqL7ol02a8yi07GEHGqOipTohg/2KL38uiJq1kAOaZqKff76XLTshcTqTW+8cnJdo=
  template:
    metadata:
      name: postgres-ins-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
