---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgB0K+bbdfrwykIl3q0ccxkrUBZeRHAmHP1F92vsUMxIfdxZG3KskegXdsjBlaFFx68jilHUFQbh6VeO//IpH6yzy+hxKMNsHBSa4msVBZHU/saBI4WQhI4qcPtqxmnlVN1kCgYzdCLsQWaXRSFFAKy2oE95NO8AfJ5nvNw63x6uSO54qK4oAx70+L595fzla3NVJPMnBMLnbH0+IJp8PdlL6k6tGMY8Q55nMQDcTtybYb5qE6I8u3iGWNMlawpg68OsS1p4qh2fKX2VvDYciDFSVcmP2UoO3vDVty2wiz8Rs1+bOfHrxopq8/nnw5dDUQ2pPxeQJTXkih4b8o0NxbNDN3gz3OixHWVMcDW0yODIHncckSS7wb8bOwUAzCj305q4l0q/TgxYhBAOYJJQkaCtBkGPcyerarOqt1sSh5Z/JpqnbQwU31qbrBOdBJmTNg4RMCBXodRfwrn+uHrdGpvmH4vX37DDyPUONhKcNYi6IMskrBRKERaGK0pLJlInRpffXcLI35kNC5rGLBz7LOz+oAbtbsLg2EFt2A/tRMELfrZj4IcC9Hj92wHPbpZa7/ig1+eCbnCRTpjMVdCGu2WduYl6IuksMCa7UpV474eMw9VSmjEpWRrYauwpYl4cMdYOLiENStByKoJCjFHK1lDeM8vmWTP4LpKsggxaC6L6i3Jm734VpkV2BKhyEMFkQyHfLNDQmw3xq7SwfKuma/PbUsUmrpZMfuN78c06ja13jg==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
