---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgBZ873PrCKRwO+Yc9bqfttbXaTLKBr19onyXIjEoXGgypDIpFUdPxxAB3IJ41oV5UeCSAW0UdZbKYrC1yCfNI/BkRliClptOutm/4rUn0LwIMqCgLU76p6bJhRuzYLJShpisldio6RpWe/crsCIB4mpBkCW6GjiKVT35ciRdzW/wQM7NqGU/xXtJOoGgBUtu6/AbcboTtDO3gSPVSfnOV/ioouky9cdP14NQqTQQzc9Qgzt9QBzy30uK0x2+lhSZ83w4W8Y4hbQ3Pj4EajZ4p//O08n+fc98/Qeb4Al1lWqXqMg7yrH8QycZjXio6wlpQsYGs9VYfwsUdILT+DKZnlD3EFA6HZkBEVDV9V7D4gHkpfviNjqED/yHhxeOERhrM5lo072op3S7HT27fbiVvsZVh6ccmQQKjAPkgFDa0wGKTQ3h6j2HAMYCETe+tkd0+lPcmtHET6pwznwKmewMrB/7OWmuJJyKi2h4Ml+D0ULatUAUeDCCKIO3hLo8avZyWGMUQVsM45VUGxqNrM16Xdy+X6V7kRBSRXD9WXPFss+gzxLaO6nXyTc44j6Mvvwm17MeMsgxXLb9K/eT2LpXvJDwP0D2RKbZRSLREk7EU7ZBvA3s1vz714d6jYvu6QkYJFJXPMb3dKR8OYZpRmDzaasb786B0BP7eBXQVxrSz0aWz8rQS57rlQyqFb2jhULKTqfwoHMqQK9iQU9PcV2M6h/gQhLPFfXbF1yIqWLqw6sWNPjtC8UsqxyhBUm3bKlGilRaNtld1DQPgFwQc0ZZIvQ0iVtwr+ySwjTree0tTfmA7jWRnVxbqgMlDmE8diBNe2jJVRhq594qDse24dpQEzQC6Pk63k/QX1DpNtazHYq9KfoC60dSlV/rKy1THcrSL+frOm42ExOilAO+NrwcVT6Kl7YpIqLjL9MBBleP1ptUHtrifZUDxFy4w==
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
