---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBcqTlaI5hKrZcyxR7lKGKnO9v0hGQ0PMMfVvBkYRjOQ+/dbVTdrhl/okJqNc7YWkA6pVZG0OHzhU3CRwsGJ0rJbUdVJA3fP4edKVozrgBp/srZ9L74zuaoqbM43tAvHDYN/yyy0923GO30RVq7QKZd2ylAI754b1Lvqw6HoXDYudDxzDYAtCfd5MW8pRRZ3qTbw5oZ5ObXHw0xbrkz+6CjJrC248cpPSiZWoWAluKneF6F7BfS0eMK8+36LaSIcj49yxmTIp/kW4Yw0XinPqJ32S6INEZPMgM5ZRE5AHf3Tw+mlcjoSvxC+Lqap43X3rtA7D8KTdHMsfp+mOTSA/l55ENCtRBJJ5zFkCsSn86DUY/B8ddNNVuea1Sbi1i/8fzCrhADq8I+RS54kQ+VL7gXkHlyBebZupibOZNdFh1fZnGG7qOFfoUDeIiuqcTZgXOXtFuQFYl65pP4VupWFsMWxDPpXlKbidgE8ekDkbD1hVzG1nHVg1iwKWqY3f3wPjcJxjJGpXk41SMry+jTyinNBGtzEBzzd//XLlv/NJab59euZEx3+YZGSIbSVz6NJNIKmAzpFhi82HvWezMKMnzRw+8H9OoHhRDgs1CqM/v0lH7otTnO//kBzzfzrqVkzid851Id4dyKDViUnxbPD0YZTUNzgc7tZ7q2e29YZhak46NQ/l9RFgW0ejucSZMwG5B7rHxxQvXBhbXJZSSkZa4RYw0g+Y2WNcbflqaIo8nanQ==
    username: AgCC7Aq/x69Nyd30zjJNiedzWroDJiKYfGc53pd6/0cq0Oy4Q41sfyMh1YRnPKI4srqzBff3sHMEbWs0Z319SwjbHqleP4D1xYZWip3uJm49e+ItywLKgWtagis+9SpQS72MAgUEnNyGMX/MY+++YVw1vrk4my+FzouA/GGuN4LipOCdPoQ3bJf+2apptrG3TBkhfW6n4nD3SPfDtqlAoa0END002SqAgpiPZgVK/Yw5suMmjeokzNSsiONyeFy+7iXP9r2yR4ms5L0p/OoIOrV3yLrrwXeVjW3cjmKdsz2xYNvEc77VrzUhZJNboTWcb705l5xIVChP6YLj+I0P6CJ1Esbis4ESNCcMhOhcgnrpRQztWC4qTJrS3OvpMLGZYv4gTLXh9/AvzHIojSiQoQVpK1JBHObkSrerBxReMllZjFpt7B+skZ2mysVacW00bmYSDuDl5VOb0xyJrQPhHQ1Lt1J8nfttFIHHJTJBGYa2TtXbvuZsMdkef+d+xVUI4DPuOoikXKX6cPH9XI7LWaOgJIZfK8nEyq03dPvzixxKYsYvHf/99npJvSLYYAYFlhcV2e4PrPY6+TKsEruSXzEL7xa/znKKCHNzvRTZndCjPbJrD9RbheLWRhAcyyDLJNQw4Lo6nT1UgJADUe/UYAd+rtxt8NCTUoj+Xrvnt6QnTEU4yVg+zATL/8bEPTD0NxJwoEgElR9I+KDulsejjpoD3H/o
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
