---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBSJnf1EIU0MXbrnxBwWPwHw7olzuJ6U5MQzBpXj6fhGyozZPQQwbNNtY9lWICZReD3ZbeGKdLsky7ylpifCVdd/zub31EGJJZH8zrY8s3HQ++EHDAKDKAoyWimoe7ZLN6okc1RhDTAAEB893kpog/BtAYv2L6qlx/uXKbRMLg5xUrh4VtxSzedwspUTq9LNmI+a6zIhbkr6gC9sKoMgdMPDRheizaQIpFVpErYYsJFVSn0TQT7uE09I6q3ZiK8Ol24hwVMxC1Xu764c+zsu8Q/qEyNj3tZbYG5PKK4d9xZ4jUZF6EFw/gorBZIOwfGSg35CHCorr9zWPs4K7QynRo9TzZLrTufpLUuJG2ZD3YfMLdYjD0pfuvbEkfJEiAR5hnPC5WiDAHfTqN4O/tPaf8l/SB6h3P1+gy7ecwrAU0nUtK76kGcZNiNAElJgKW2UFsr6XbbMlTMcuxuIgKHV0D9X1WF+MnHtoztAv63X1CBy2Cqge1N1zrZG0JO8to1/iL6pBO9ebuPgcxyyX7osuaIRv+6eJcTj7++1dPCo3cBMg40BBF4zwj4duGP/E8h6OlHQP8dK1qbANAPm8i71YeJLwvsRWU6Y5zzwBNBDTmq4+nxpzeiXfZ9qHLAfUfivEM0FyxmB/VJAplVZwJbt4a2DQ/K4LRSJyGf5T8RHDhAd/QgSOFL51r8Vb9efppu+XjgVOH9XS6flDgFjz/DBZ1Oy67oSXrjihsLhlkUUgLSxw==
    username: AgAuzX2TqRpMW89RYu8vVxoGYvEF3snJJlxCLMhMcolsIu6v+Ui0y/GiCcdhvf5OyhQbx/J5KsipYfCaRsQ9GBMH9Wyx57BLy98cghPWMPUndfBhFOGRR/VcnnzT9/x9wDoJom3HgdaK6lsjXavH/OmsvK2pCSYE/Ae4kBLmx89Ol3yI6deR42+gpN8m4F2SYa/1ZgRC/0tYoWRAV1mX49vb153/ALqKJWL9cR4L0yUDhgjFPm2O9uF+XC7AO6dytDMecTWuiLHWGsYw1TjxmxtE0B4mzZ6AYxmq0kEsAif8RJWzhZYJWgqnwsSSpp+gtBb+i0wfJqoFT3bYaRuz5+6rVB7hotY0JqNon95FvovIlibxv2ljb3Pz8BS+5bQp0g9g2CSqtXoM7h7aY9P+ZJP7smy2/bHISk80ieenPviCHjV/h3S9zhrC80Ke162WutawZ1njyFgny1+JYvHV6BGv8C1LXuKZuntHPC4rYrUu+5My7p+N746CVJjLat2K/TF5tjLdqy2TJ83xDUK1D5X5AtrsFtGPYQjgW3Xpz0bC1nCgVfMtaaSQxu+eevH/ENJMAtX8I+2WH9ElA8Tgaer0NAduYyYBMLoXN4RZ9tbeSxoalT4IVFuU4f+++kTwZY9srSytm66AQjvfErDNlBKGMqmkq0mqcvBrFeqFrnBw8HDbNZCNUIYgSL61ouEgD1rOlCh2i/fQoaehye4JauSKUCKH
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
