---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-userdata-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgAol1veZQGWz6FrkN3eQA6x6L0wE5vUWAcmgeOIfC/nHbay6MUFl0owpqYWP/NjNG5JjxhZ9KX3Da0fK7BbGGnP8XBBiUCrQtyCoH9R1OEniei23Kr65roAPD7uyLFO7eB28zRenmOtEiWwNPpBZfaYwNA6eWwsdKhfYgyYfEOePXK4Wn7FKUGKkbDfP6XC1NaxSB9ujJNws6aWuaCqfSxGT93MCZ9fSxwBza/WaKyvcnpBVsooCDN8ltAzRl68kjk3krJFYHBUMO/+oarbXZtBpVJwZADa3jQj37eB/skGqK5fCHUg+kiKyZPJua2RAJYq9RHslE7/vKciX8GcFgldFun8IuFJ+1G17C6q9aFC1qQKTEto6A1SGISG3HFVJ4H/WDuJ5wBuc6tcdbj4Hvt0ZOEFQAq+86rYHprSEkf4W5TrL2DzjQvtvPLk48WU8RwVQYcVqwlYuksIvisI+04SqpGETCF4YSmakwiDbketu0rcSBb+YTkoub/1YgrYVCnP5TdOL7I9wwFKIeMgJ+J9bLnyJ4+ZqIP29gvhbggC0vpACKSC7Tkf9gnQMBSmtRpLikTrf253vwlOUCnsDXY3Qii+1RODNMCz1HrHxkJN8yOHcRLbR6dAvE+udOv2cS3/VadNsRxufn23BUG6UROGNpM5cPqUvpMjZL0HM/tiaA/IFonayE/21QlB/nVojW2X9UM9sdGFaoU1NwMhk0VsbIi16/gvbjE5PMlhkqBYCg==
    username: AgCqOPYr3UrEQgrmrZxiSepsYhi9n8OCbb/kptansvOHfw6iCTkgWqohN/tZ7WbS+WJ95yQYn1JBc/lr1qlzRaj2y7NifMtwFCcT9HZt8U+sWORw5SHCPDMNOZatvRxp5WGcdKYDRyxviLO1YL3fnFXbgOqyu2ESrhGzaD3BWSyRbaLu8KzuHPUeRIgTLe6Z7rfCLn6kK7oD7JrXitJDKQ7Jq85gwdN7URIOGk415x6+60US9SNlFypPFJu3QwgOx7tSeRAEhnozwfLjkrY2lQ1YRxM7b/+yBIZTniJSWEpDzsQSTBTdajcEfTLJWqfZhaeDUSuKlsHhDYYyNMvYdl9g/Uu+YYLpbttp6xyYy8T9L0ddVedbsz0HH9fAaUgaXKMtTfXur717m8eC/5dkJys3AxNaMoiPAMeFD6nNFWzMXCfQWC0reRcPrNv9x1Snpem+eHyS5M3oBTKYYiknUA8rtKLawqUBoq+EPdo5/xC+tIh3yIElF2F6mhekMEF5P4CWSY5GCST7aCtAJBjp43gpsApiJQ0QAP+UiD6OClQNci0fawjwaGKsfBzsefSXbn6ewxHUTinlV1hKLe6s+MWSu0+V5XBFVqesIYfIOEXRINcG5Yl0ZPibLQC0rQQTMX1C1ZrgvMDiI1SKw7I7iLQEVVAglfsr1nU+Di69MF/J9ZRF/ukX/a/iXnd0Qsvj3IvRmqRjdy0LexnvqenYb8Y3rOpE95nE6jjr/wEwZA==
  template:
    metadata:
      name: postgres-userdata-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
