---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgCCrfHawtc62c4XARXOJdEU5U036yTf7jFT/yBfzwvRgME6KcXMCJY7V2vlzMIeY7iv+YwF5+5SfaubE0yNBQPDDkA0Am8vguNwKFl/FXAGR7CXxXNvE9pGT49bHCLJ5viZmsbBem8zsewkEP5jkYSQWWfVjm7rQWzsQ61tN7jiU8Tl8Y2cAGOXk4LVb5xSA3HHobOZfmomB7NfNZHGfwtLMwCkgLCVbjW/QXoYb+ZysmYjZHeYhF3LAQ+hkQdshEts3BkgP/RkrmC0wLxAzI8+t/jiOJYnVNK/DGh9mh/AkTm6+Mhc6rgGbvelA+lbL/Dsu1yF1wqdBrEWQ2uWJ8Gic3kE+TzLXhrP1cRnM4KMsEQK9JTWhhrSod+k7I2vpkpZUrTnT2xBUyz1AxvQmQZof2u+ZA/gW0dl465Q3cpyN6jrW2IjPQJ6SiSv00H9dlXW4BuE/8vpanmyocAb6Lzl52PNOw3CAn6NdbtJGv1CmILBc6lDvJIKP4RMoILfpnARYn+F9T1fD+M/C0T0yZgBO8I5xwCl5kXO99NwpOq3NM3J0Yey9zxd/zlEkP30oLbQvoP1lEsclQX600Gc2HDo1wPSJ9wCIjYiOj8k3jMd0H9VmymA26iu0MqdvzociuqH/Tt8/UQzFk5rgMYvYPqMabCyXdd3oExAVgMabI7fpJfZOF1Ii1Iv+yi8T3n5PVcEe6Brat4FgsWZ4wZqbMNIkE1fcODvQy7JpTN8/T27BA==
    username: AgBda+eQaPfSPuAnnCbrPkFu2xoeZwF9JnFMmi11PlrwWeRMFKkvPcQjYWjFNrldyyU5HhLAEt3aIMlgcgmgYgNbSC5hEZQ8cmpymMHqs4xZyNgsm8JdngKFVbOcZ+Lup/m4VDrMDNsDEwPzi/wGdwPY5zeeXc8fbiCl/T/U/0Poqu5M4xU0CkqrZ20s0N+QW80BO8JhijXuXnp1ftdmI1QzDRZzFtSN6Pynpbbm/tK7iha0io+KSEDYUqTwRasWgOx67khDuef6M2cYpw949jLolx026o57NV7ZB82ffJTGPUq7ig/FpFazjkKCwa/QTm8x7jOktIEXsaQuQnedwn0JIkJ9Y1yxxatJA6WlQ4ujCq4DRwRfG3TrtfrUbgh3VFuzlbDYF+7kSk59yrUqWvBvHwxcN64OKAhKnEagW46wdOF4SeyAYSQMp1TwsU8BRJxBC9gzHIbI4p5i3C+XLxS+8MxZQ8SNjc08F8HRF4P7IExH+9HHLrOrB0a4JevJ1B2VGRabnTuX12Fts2rnq+ZPt8eMueKC+Qh1BK+QssZBjT8e7RuNn5DF4arkPYrVFwWT/MZFedvJV6rTBWSiYo8n2Pty9cQj06sMF3qiwjY2PEo4Ms2+i3vuvFDeYfJWpYr6vo+C7wA2qWyi2xx3RmRZ0X9cre2RkPUtw77RptMjcolSK/DSMeQwopMuj7jugPQKZWkcTS+eZSw6F+56mfYa/LdK
  template:
    metadata:
      creationTimestamp: null
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
