---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgB7C90KyKBqGJfnH+w/4F8iXgKIPc6SQ20wUABEGbAZMivyIIhcSboo4BVZ/Vabl9HcxKLyTG62TnHJsejYOjf+GIWIQTjFaroXJHX8LCQqrZHKZUs60PnjNTXMhEks6wCOJRQ73N3HNCjVBHCFhyhVtljgylbclunfw1wjyUFaiubtmZo6DEGcB5+5jIDJEGPhe56VIfY5QHYph8j5xwOYTBI73Qdw+1DuQyInIjcK/oN8C+OsPqCeHvbDZrcjn5enVfRaC0q2O90IPQ2XnYqje1q33TyePBG8YJmFAoUm1rGj4rI/FH1WLDsHy0nVMgfof1tmeRg7Iq1YnA6bfWoa5S//W9MfL/T2otK6/4GZbzarTNxwe36aJDsdpv9bpfCKYCitnqPAeaXsyfWDpL5oaMPSy4vrPBE1sG7l6tO2byloFtOQMJzQVjue4vcKeVgVEMwyRu5TamAe+uXjOSWMCGZRLu5nhFYt5zKol8CrdaNSVZRRNZD2uD1AK6ki0ABcZQDHxO8uSQPO510798dEoWSiiCYPL+k2pJ3wRRt34/6CizsFbxN8DyLqegnGJ2tespjLCXRB/omzRtSt58F9cY6Wuc/X+1Gf46nFasfwJf5IFuzMl1i0FixwqVpgUWe1QOa0+IdLJWwhQa+fJFAF28Xr7+MQSV5zoOLsTyc9xmd0L/biPnZ5kwV6Fg3WpEYErpbcu405Tdhl6ToM6s8OIMewTSJY/aOKx+0lTRy+zg766wTa76l/MejucO75n+PxY8NHTYmbIDg3B6lbzGa3dxvXNZz7VapeqHJInUMp2rx+XNPtj5nPX/Vdw2LXMae4T/Nqzz4KetBH5Aom4GNNVZBHnMDbGUMOklcWXf0f8YZHvXus8GhTmM8IFD6zpnsJ+uhaoGaRLBnfbb76ID+hbM5LbLUImIJ9OP+f1svVmnIbej6lfMZenA==
  template:
    metadata:
      creationTimestamp: null
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
