---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAFjlxvQtgUeGn3yKtOsvecogGExWan2aUVcxDpJL+ChTaFHgZjZnsjuhdVIkcj+eqk1ybGP/HxnvbGCyLO1M/QyblihuhnIuDdTiuosafr9kOHTDoAcra17JS2c97UMJh2a7F0W+R9nj+2PoiIgGaj4LhDro+HknNP7sozv7BubVbjSLo0HAz/glNbshzBZonWmQCFXL4whYG3k8mpTcf8ZC5dIvOOV52b50R2DCNtrJ6Zf2tFBDsNMxnn+f9dBheMS3nLUadHlQeOklYIuYj8G5r1IQKTilAAHMaEYDHlLgh5Bm+RMDKV8PzUM4RAKE6w+B4fxsQZk324PWF4gnCDst1I6aMj9WLqLC1rW7wbrFNIvzcmQOv4lAllAAlxhC+HiCpqqxvosmOKzlnw6gf7sBgN1hSjEw/MnN9ZWqNBy3Bw7YpMm8PfV95nStFjmWBmnKqdEuMF2Yyp2aeVVBIkJ84zThx4UXsWwbk2tceRM6BCfPZaGftukyglO3ameVBpTbltxiwIhxgxdWsvjryYAzFMRFntc8ZwixrGq7nGWNuKuIchCaEdeE0WR5fxJhMAccb87WGmwEJYkOgbI0kMKTgpMQQHZBGkkjiVQQZWWt1IgeRgZU6YUuQFV3TG14MEY+xjLtTR+/dDSwP5w3+jYBkpYLQO3RPPWJNSXeFR0isfzhNDPp20p+YUowT2MNhGGAh1exZQagNh0Uxt48EXP3ZF3Owgbh6CHF9XYJ5U1Q==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
