---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-deployment-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    password: AgBzNVTDPNpXe/y/iw+Gk3qT42diMCo2wdhCnbFnOziFZuZTq7OTSfLuQ3g5gidSywLzGsep1EnK0Fyz6IJuwa7Kf3Q0eXMHqiYP6H03vDTCx4tH/XZ5KYEvoMjv1fZeVV85yTzvq/dTMqPAIWtQvHcbPDeCQFsVLod7p813JAVBazrrZIgtJmEmekvzxy4oiFq06uFq8FeYW2GtqMj8VD6p2cqr12h8EOMmMvHx4p21scPpOAFkbwYYOwLmTq3DdoJuBPHT+tCq2QaXRbEs12Ob64ox4yqXbRiJ2Tb2BOn9VTGtK/DwB94H817pPQbAi2ayCPBhTybNjMzzavaSMlcxB0UDefjOBkAJx/WzWztIk8rrniULvUoa/iQWV5eRgOhsM37eV0KaV2qBk5LpOI8GpBc/UF+hj0E9x+RbSlgNCMVgxCs1Lel9uGBYmt330sboUAArtnMQFyB27Wsp9lJjaxm1TK8BwIK/fAsj9y+RsgGsLE9o8ZBmK09gy3WYT8o4jeKBOeSKs5phqgTckAUoUAQYFwnbLgL7s5R+/C12mpzypBZbvuw8YSmKZ/RTEpo93OdtLhBH087Bz2t2523BjEr3+rhgXb9xDesdHZGGiOWsGe8Xa7Y6Cabq5TyvBozVZLNjYoU94HgcCCrBfwpkAoV4Gzi4xGEZ0rprusjQ9GtJ0asIIrii2F4G3PJ5JMJEWwlBYlHBVjWqcJsqjcVFoQ5KoJ5HNUOJORJa4da1cw==
    username: AgAzXu11ko7IwBuztw8leONFyEy6NLFSSUrtABgtXFMNJ4dBwNWx6cOIrAyZOgzArTJmOOJNlq2XOx4pYx70pGh4O3s3UB5lmcUcPr6MlJikTq/JVA0iaAoCDYWisoMb6KOC8wkGVRciaSI1OKEClb0nHMn0h8Ywkg2OxUi24M3pzglGzOwMcKUnbDKsVY/3sptfsegDgniOB5zRNBP4INZUGOo9DmjgThDoX2ly8zQlH8R2Tnd208dpAZ8xW9Cd8USXCTejHLpd8Oue6aTrwXdQTfZ+GGZYoZtDbL3aZRyqjg5IsVf4g9h0Fz5/BaN3rhZWJrFPHINXK86+uiHOUba3BKCj9favnwigKaf0WTK9CiL6tGoiVhUOI5PousUIJI6CNl9xk1jdbbeBgBDvlEY++a5FLVGFo+L+RzZM1fPtv/SDDUrerSCy4u5tG9TxTI+tRx/OnXwQwizi0JPiGeeuvelM3t+jpTnTltOkfs6n3g5D/LIrE3oeexySl76R37zi6skrbi8kvoP+d+5lsAQRS/qUl01M7f1eQcMKx084aKy7nCxnVocuDLuIGTudAYdZlZKd1vrtqurz1YE3IjLO4t7HO4bXgp7VsZ52h9fc0Dx7RS45E72rb3fFyrpz+X/yXg4j/3btGqahze3zU3+X+JJgeXcF34oXICBhR8zeGyVTsU4ufj7Syn5jH3mkG8X2aXyRlxPdBQ8IgIq8GJCOHPhb
  template:
    metadata:
      name: postgres-deployment-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/basic-auth
