---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    .dockerconfigjson: AgCpEShz48915Pj5fy7miL13+BkKIgab3g5VUpgXLVcWyf3tE32XgmT88PiXJmb57AC1rcHQfhE2CYd1JX7G0L2H2djx5PjIcfh90PLdG719FcCjrrUiQ3TexxT4vxSoYgAvqOOMy9epmsl8NwOLwdAqyTbRwJGdGpbTqtQ+w6FaVYBybfWMr5YYXdZfL80+bPblXw+ZclIvofhILzNhT7stVybLluw2TIVKcHCo4xNlVvfqjJEa9qpAD15PuF0KKTjoJcMUPAxjX1A4kzHNgqVOpHFl1q4DE2C0VMh1cumBopj3U8HBfAn07zsQtHhoSAkoWZtLdOQaRcx56Bo90U0LlXLNFLi83BKSOekikUbRqIpjzUUg7lP8EBMPfoknMlPwjoROXu/9bFu/0cDYqtG2vy8gtQiio2iYUww0A7VeMgAlksaas4m/f8zPHAS4qDYHNwIrdL6e7Dbt6FTgweOzB13VdUBv3sKhcIZrmKBBrmK3Sk5vUWV/OfPXxb7bBqV5VT43mUa/2tXeJoLchkex4Y0FbdV5v3/sbpvDYp5vIyuEDkUxzOCTrLcCItdOsNqxPfnqPOK5/Wfc+QrZDAKSxuWIhVbSlS8vOqsQE5HXv6AntfVF44EcEyBjEoNko5L80iRjsuUxPpy4sPPqMJ0Hqb1tFlHanw5/9bTDuoCvhNhMUZisKaw7XRDY9V2AU3NgSz6dHxS/OTUe2uaWOy5DfrV8lz9FsYC5AQKhxwonr3oO8jeHrKoducGE+QGu+NxdC+Vk1QqjKtdAhb/NUv+ma9/tShLpO8zhriKMqIuPZ6N1+PxI+nJnL+s8lJ/6AkusyHvbaxre5vJyvuydV14k6iQ7ZVaztS7ZLJ/AOpgWNgVkmpCyI+5liLb3CYtHTMsg+izzHGkUl8eG+P9OKx/xMbbh2IS+lqvrlTpN4rOLga3MY0MMud+4qA==
  template:
    metadata:
      name: registry-credentials
      namespace: hack-for-facts-dev
    type: kubernetes.io/dockerconfigjson
