---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: hack-for-facts-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  encryptedData:
    REDIS_PASSWORD: AgAGpIoD24bIM+0I6KyKXid7irZZY8W1ghYEi+EN1iyBFWopdkcfyjU1/B37wFZEv1drUc4ePHPutUJfxxLV9c5DD4ID0j6JjjLHfcQTi9pmT6nHrnbOjuIXTRtrivya3ZvjvUaudCdsYYYh1KX6MsFGcsjHEKUwOTRYmtqHuhoepws1mqVYOAR7Y4GXvKaFfBxSALaXAO48wrqH5s+aeD3QWSCyu9Ok0TkuzrXedFA/sa3u7lHEvIqgnX2M33Ais9Au4+EKXkLK331/mghA1tXlqJMlEsWiT+elRnQBIRYb7Yslr02LyFtQkjgZ4WJOd5qkxwZRe9y+NWTa/ovJ23Ls8eJqXKj/l+geT1Y47sevFmYoTlmYQ8yWdoIQQrNQYWsX1SgTnlz0KK/OukTx1I6jcMF2caU8zyCHeQHVI1IBNQSDhbSOW0f0f29nkme2ER++nYLKduRTTY2M/EL6xmSLMbuVUNzu0eQBhMrVQtD7NGjwg/EIfcQby37dyIRWHLpZ8aq/8pMdocScZnAwHoTellydawoEnC6M+XZP6CiFNvQhLq0AL0pm2vGN6g8cH9xnI20oOia9kdsedr3GdfRLAbsMe8Em2hPYDnmaziOY3PIHXNjlevomAezY0xuULYwuP0oe8ho1ZUxAs1A5gaFcwGWcU1ZQRzorDYUDLREDmU00EpCc/1I8ZYPDAjLF6FxjP6NaYINGnP54EJIGnSSUQ0O+5z5IOKnds21ArLgLWg==
  template:
    metadata:
      name: redis-auth
      namespace: hack-for-facts-dev
    type: Opaque
