apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-ins
  namespace: hack-for-facts
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: Delete=false
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.0-202511100807-standard-trixie
  bootstrap:
    initdb:
      owner: database-user
      database: database-name
      secret:
        name: postgres-ins-credentials
  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      max_locks_per_transaction: "256"
  storage:
    size: 200Gi
