apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-userdata
  namespace: hack-for-facts
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
    argocd.argoproj.io/sync-options: Delete=false
spec:
  instances: 1
  bootstrap:
    initdb:
      owner: database-user
      database: database-name
      secret:
        name: postgres-userdata-credentials
  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      password_encryption: "scram-sha-256"
  storage:
    size: 50Gi


